package com.descentmtb.ski;

import com.descentmtb.entity.BikeType;

/**
 * The ski models, each a real pair: maker, model, length, sidecut radius, waist width and the weight of the pair with
 * bindings. The numbers drive the physics (see {@link SkiPhysics#tune}) and the model / texture (generated by
 * {@code tools/gen_ski_assets.py}). Each one is its own item ({@code ski_<id>}); a placed pair keeps its brand in the
 * entity (synced by ordinal: only ever append).
 *
 * <p>Colours are the graphic's main colours as 0xRRGGBB: top sheet, second colour, accent (lettering / details).
 */
public enum SkiBrand {
    // ---------------- race (alpine racing, hard snow, carving) ----------------
    /** FIS giant slalom ski: long, stable at speed, a long-radius carve. Red top sheet, black, white lettering. */
    ATOMIC_REDSTER_G9("atomic_redster_g9", BikeType.SKI_RACE, "Atomic", "Redster G9 FIS",
            188, 23.0, 66, 7.4, 0xD0202A, 0x141414, 0xF4F4F4),
    /** Short-turn slalom ski: quick edge to edge, a tight carve, nervous when run straight fast. Black, white, red. */
    ROSSIGNOL_HERO_ST("rossignol_hero_st", BikeType.SKI_RACE, "Rossignol", "Hero Elite ST Ti",
            167, 13.0, 68, 6.6, 0x17181C, 0xF2F2F2, 0xE2231A),
    /** Race carver between the two: medium radius. Fischer's black and yellow race graphic with red. */
    FISCHER_RC4_WC("fischer_rc4_wc", BikeType.SKI_RACE, "Fischer", "RC4 Worldcup RC",
            175, 17.0, 68, 7.0, 0x101010, 0xF6D200, 0xE0301E),

    // ---------------- freestyle (park, jumps, switch riding) ----------------
    /** Symmetric park twin tip, playful, a fair carve. Bright Armada graphic: teal, orange, cream. */
    ARMADA_ARV_96("armada_arv_96", BikeType.SKI_FREESTYLE, "Armada", "ARV 96",
            180, 19.0, 96, 4.6, 0x1FA7A0, 0xF07A1A, 0xF3EBD6),
    /** Wide all-mountain freestyle twin: stable on landings, floats in soft snow. Line: purple, yellow, black. */
    LINE_CHRONIC_101("line_chronic_101", BikeType.SKI_FREESTYLE, "Line", "Chronic 101",
            178, 18.0, 101, 4.9, 0x5B2A86, 0xF5C518, 0x161616),
    /** Light, poppy park ski with a short radius: spins easily. Faction: white, black, red. */
    FACTION_PRODIGY_2("faction_prodigy_2", BikeType.SKI_FREESTYLE, "Faction", "Prodigy 2",
            173, 17.0, 98, 4.3, 0xEDEDED, 0x1A1A1A, 0xD7262E);

    public final String id;
    public final BikeType type;
    public final String maker, model;
    /** Length (cm), sidecut radius (m), waist width (mm), weight of the pair with bindings (kg). */
    public final int lengthCm;
    public final double radiusM;
    public final int waistMm;
    public final double pairMassKg;
    public final int topColor, secondColor, accentColor;

    SkiBrand(String id, BikeType type, String maker, String model, int lengthCm, double radiusM, int waistMm,
             double pairMassKg, int topColor, int secondColor, int accentColor) {
        this.id = id;
        this.type = type;
        this.maker = maker;
        this.model = model;
        this.lengthCm = lengthCm;
        this.radiusM = radiusM;
        this.waistMm = waistMm;
        this.pairMassKg = pairMassKg;
        this.topColor = topColor;
        this.secondColor = secondColor;
        this.accentColor = accentColor;
    }

    /** True for the freestyle twin tips (turned-up tails, ride switch). */
    public boolean twinTip() {
        return type == BikeType.SKI_FREESTYLE;
    }

    /** "Atomic Redster G9 FIS" */
    public String displayName() {
        return maker + " " + model;
    }

    /** The registered item / texture name: {@code ski_<id>}. */
    public String itemName() {
        return "ski_" + id;
    }

    public static SkiBrand byId(int ordinal) {
        SkiBrand[] v = values();
        return ordinal >= 0 && ordinal < v.length ? v[ordinal] : ATOMIC_REDSTER_G9;
    }

    /** The default pair of a ski type (old saves, commands). */
    public static SkiBrand defaultFor(BikeType type) {
        return type == BikeType.SKI_FREESTYLE ? ARMADA_ARV_96 : ATOMIC_REDSTER_G9;
    }

    /** A brand that fits a type: the brand itself when it does, otherwise the type's default. */
    public static SkiBrand forType(SkiBrand brand, BikeType type) {
        return brand != null && brand.type == type ? brand : defaultFor(type);
    }
}
