"""Descent MTB block + item textures, rebuilt with the mcpx toolkit (tools/mcpx, vanilla Jappa-era rules):
every texture is an index map painted through a hue-shifted Ramp; noise only picks the shade.

    python tools/gen_textures_mcpx.py            -> writes a preview set to build/tex_new/{block,item}
    python tools/gen_textures_mcpx.py --apply    -> writes into src/main/resources/.../textures

Layout-bound textures (barrier_post, cloth_barrier, trail_sign, wood_support) keep the exact UV regions
and alpha masks the block models use.
"""
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, 'mcpx'))
from mcpx import (Ramp, item_ramp, composite, noise, white, voronoi, quantize, cleanup, bevel, rivet, ring, disc,  # noqa
                  gauss_weights, grow_clusters, lit_edges, mask_from_ascii, shade_item, stick_handle, save,
                  contact_sheet)

ROOT = os.path.join(HERE, '..')
APPLY = '--apply' in sys.argv
OUT = os.path.join(ROOT, 'src', 'main', 'resources', 'assets', 'descentmtb', 'textures') if APPLY \
    else os.path.join(ROOT, 'build', 'tex_new')
S = 16
yy, xx = np.mgrid[0:S, 0:S]
BLOCKS, ITEMS = {}, {}


def B(name, img):
    BLOCKS[name] = np.asarray(img, np.uint8)


def I(name, img):
    ITEMS[name] = np.asarray(img, np.uint8)


def V(base, n=8, spread=0.30, **kw):
    """Vanilla block ramp: small steps, low contrast."""
    return Ramp(base, n, spread=spread, **kw)


# ======================================================================= blocks
# --- packed trail dirt: loam, flattened by tyres (stretched blotches, fewer extremes, a few pebbles)
DIRT = V('#7a573a', 8, spread=0.30, warm_hi=8, shadow_hue=20, cool_lo=6)
PACK = V('#80603f', 8, spread=0.24, warm_hi=8, shadow_hue=20, cool_lo=6)
PEB = V('#8e8b85', 4, spread=0.30, warm_hi=4, shadow_hue=260, cool_lo=8)


def dirt_idx(seed, cells=(8, 8), sigma=.25):
    f = 0.5 * noise(seed, cells=cells, octaves=2) + 0.5 * white(seed)
    return cleanup(quantize(f, gauss_weights(8, .5, sigma)), 0.4)


def pebbles(seed, n=4):
    peb = grow_clusters(seed, n=n, sizes=(1, 2)) > 0
    return np.where(lit_edges(peb)[0], 2, 1), peb


top_idx = dirt_idx(71, cells=(4, 8), sigma=.21)
pidx, pmask = pebbles(72, 4)
B('packed_trail_dirt_top', composite((PACK, top_idx, None), (PEB, pidx, pmask)))
side_idx = dirt_idx(73)
crust = np.zeros((S, S), bool)
depth = 3 + (noise(74, cells=(4, 1), octaves=1)[0] > .6).astype(int)
for x in range(S):
    crust[:depth[x], x] = True
cidx = np.clip(top_idx.copy(), 2, 6)
for x in range(S):
    cidx[depth[x] - 1, x] = 2                       # compacted underside of the crust
pidx2, pmask2 = pebbles(75, 3)
B('packed_trail_dirt_side', composite((DIRT, side_idx, None), (PACK, cidx, crust), (PEB, pidx2, pmask2 & ~crust)))

# --- trail deck boards: 4 boards x 4 px, dark seam, offset end joint, lit top row, nail heads
WOODD = V('#7f5c36', 8, spread=0.34, warm_hi=6, shadow_hue=30, cool_lo=12, hi_desat=0.8)
NAILR = V('#6c6c70', 4, spread=0.40, warm_hi=2, shadow_hue=260, cool_lo=8)


def boards(seed, wood=WOODD, nails=True):
    f = 0.6 * noise(seed, cells=(2, 8), octaves=2) + 0.25 * noise(seed + 1, cells=(1, 16), octaves=1) + 0.15 * white(seed)
    idx = quantize(f, gauss_weights(8, .55, .2))
    rng = np.random.default_rng(seed)
    nail = np.zeros((S, S), bool)
    nidx = np.zeros((S, S), int)
    joints = [11, 4, 14, 7]
    for b in range(4):
        y0 = b * 4
        idx[y0:y0 + 3] += int(rng.integers(-1, 2))
        idx[y0, :] += 1
        idx[y0 + 3, :] = 1
        j = joints[b]
        idx[y0:y0 + 3, j] = 2
        idx[y0:y0 + 3, (j + 1) % 16] += 1
        if nails:
            for nx in ((j - 2) % 16, (j + 3) % 16):
                nail[y0 + 1, nx] = True
                nidx[y0 + 1, nx] = 2
                nail[y0 + 2, nx] = True
                nidx[y0 + 2, nx] = 0
    idx = cleanup(np.clip(idx, 0, 7), 0.35)
    return composite((wood, idx, None), (NAILR, nidx, nail))


B('trail_boards', boards(21))

# --- trail rock: rubble stones, lit top-left rims, dark joints; top variant with moss
STONE = V('#868a8c', 8, spread=0.42, warm_hi=5, shadow_hue=260, cool_lo=8)
MOSS = V('#5e7a33', 6, spread=0.30, warm_hi=10, shadow_hue=150, cool_lo=10)


def rubble(seed):
    cells, _ = voronoi(seed, points=8)
    rng = np.random.default_rng(seed + 1)
    tone = rng.integers(3, 6, 9)
    idx = tone[cells] + (white(seed + 2) > .8).astype(int) - (white(seed + 3) > .85).astype(int)
    joint = (cells != np.roll(cells, -1, 0)) | (cells != np.roll(cells, -1, 1))
    below = ((cells != np.roll(cells, 1, 0)) | (cells != np.roll(cells, 1, 1))) & ~joint
    idx[below] += 2
    idx[np.roll(joint, 1, 0) & ~joint & ~below] -= 1
    idx[joint] = 0
    idx[joint & (white(seed + 4) > .6)] = 1
    return np.clip(idx, 0, 7)


rock = rubble(61)
B('trail_rock', STONE.paint(rock))
moss = (noise(66, cells=(3, 3), octaves=2) > .58) | (grow_clusters(67, n=4, sizes=(2, 4)) > 0)
midx = cleanup(quantize(0.5 * noise(68, cells=(6, 6)) + 0.5 * white(68), gauss_weights(6, .55, .22)), 0.4)
B('trail_rock_top', composite((STONE, rock, None), (MOSS, midx, moss)))

# --- roots: dirt with winding root strands (lit upper edge, dark lower edge)
ROOT_R = V('#6b4a2c', 7, spread=0.40, warm_hi=10, shadow_hue=25, cool_lo=10)
ridx = dirt_idx(81)
rmask = np.zeros((S, S), bool)
rr = np.zeros((S, S), int)
rng = np.random.default_rng(82)
for k in range(4):
    y = float(rng.integers(0, 16))
    slope = rng.uniform(-.5, .5)
    for x in range(S):
        yi = int(round(y)) % S
        rmask[yi, x] = True
        rr[yi, x] = 4 + (x % 5 == 0)
        rmask[(yi + 1) % S, x] = True
        rr[(yi + 1) % S, x] = 2
        y += slope + rng.uniform(-.45, .45)
B('trail_roots', composite((DIRT, ridx, None), (ROOT_R, rr, rmask)))

# --- wood support post: vertical boards with two steel bands (rows 2-3 and 12-13)
POST = V('#b08a52', 8, spread=0.30, warm_hi=6, shadow_hue=35, cool_lo=12, hi_desat=0.8)
BAND = V('#a9adb0', 7, spread=0.45, warm_hi=3, shadow_hue=260, cool_lo=10, hi_desat=0.6)


def post_idx(seed):
    col = np.random.default_rng(seed).random(S)
    f = 0.45 * col[None, :] + 0.35 * noise(seed + 1, cells=(8, 2), octaves=2) + 0.2 * white(seed + 2)
    idx = quantize(f, gauss_weights(8, .55, .22))
    for c in np.random.default_rng(seed + 3).choice(S, 3, replace=False):  # dark furrows
        y0 = int(np.random.default_rng(int(c)).integers(0, 16))
        for k in range(int(np.random.default_rng(int(c) + 1).integers(4, 9))):
            idx[(y0 + k) % S, c] = min(idx[(y0 + k) % S, c], 2)
    return cleanup(idx, 0.38)


pidx_w = post_idx(31)
band = np.zeros((S, S), bool)
bidx = np.zeros((S, S), int)
for y0 in (2, 12):
    band[y0:y0 + 2, :] = True
    bidx[y0, :] = 5
    bidx[y0 + 1, :] = 1
    for x in (3, 12):
        bidx[y0, x] = 6
B('wood_support', composite((POST, pidx_w, None), (BAND, bidx, band)))
RINGS = V('#c4a46a', 7, spread=0.28, warm_hi=8, shadow_hue=35, cool_lo=10)
d = np.maximum(np.abs(yy + .5 - 8), np.abs(xx + .5 - 8)) * .55 + np.hypot(yy + .5 - 8, xx + .5 - 8) * .45
d = d + 0.7 * noise(33, cells=(4, 4), octaves=1)
ring_idx = np.where((np.floor(d * .9) % 2) == 0, 4, 3) + (white(35) > .7)
ring_idx[d < 1.5] = 2
edge = np.zeros((S, S), bool)
edge[0, :] = edge[-1, :] = edge[:, 0] = edge[:, -1] = True
B('wood_support_top', composite((RINGS, np.clip(ring_idx, 0, 6), ~edge), (POST, quantize(white(36), [.2, .3, .3, .2]) + 1, edge)))

# --- trail sign board: 1 px dark frame, three boards, nails in the corners
SIGNW = V('#ae8a52', 8, spread=0.30, warm_hi=6, shadow_hue=35, cool_lo=12, hi_desat=0.8)
f = 0.6 * noise(41, cells=(2, 8), octaves=2) + 0.4 * white(41)
sidx = cleanup(quantize(f, gauss_weights(8, .55, .2)), .35)
for y in (5, 10):
    sidx[y, :] = 2
    sidx[y + 1, :] += 1
sidx[0, :] = sidx[-1, :] = sidx[:, 0] = sidx[:, -1] = 0
sidx[1, 1:15] += 1
sidx[1:15, 1] += 1
nm = np.zeros((S, S), bool)
nidx = np.zeros((S, S), int)
for y, x in ((2, 2), (2, 13), (13, 2), (13, 13)):
    nm[y, x] = True
    nidx[y, x] = 3
B('trail_sign', composite((SIGNW, np.clip(sidx, 0, 7), None), (NAILR, nidx, nm)))
B('trail_sign_post', SIGNW.paint(np.clip(post_idx(45) - 1, 0, 7)))

# --- airbag: quilted blue envelope (Aeronautics style), seams at 4 and 11, orange valve
BAG = V('#4a46b0', 7, spread=0.22, warm_hi=4, shadow_hue=270, cool_lo=8, hi_desat=0.8)
VALVE = V('#e07b25', 5, spread=0.40, warm_hi=12, shadow_hue=30, cool_lo=10)
f = 0.4 * noise(91, cells=(4, 4), octaves=2) + 0.6 * white(91)
aidx = quantize(f, gauss_weights(7, .5, .18)) + 1
for s in (4, 11):
    aidx[s, :] = 1
    aidx[:, s] = 1
for y0, y1 in ((0, 3), (5, 10), (12, 15)):
    for x0, x1 in ((0, 3), (5, 10), (12, 15)):
        aidx[(y0 + y1) // 2, (x0 + x1) // 2] += 1          # puffed panel centres
vm = np.zeros((S, S), bool)
vidx = np.zeros((S, S), int)
for (y, x, v) in ((12, 13, 3), (12, 14, 2), (13, 13, 2), (13, 14, 0)):
    vm[y, x] = True
    vidx[y, x] = v
B('airbag', composite((BAG, np.clip(aidx, 0, 6), None), (VALVE, vidx, vm)))

# --- barrier post: wooden stake (cols 0-3 rows 0-1, cols 0-1 below) + reflector cap (cols 8-10, rows 0-6)
STAKE = V('#9c7445', 6, spread=0.32, warm_hi=6, shadow_hue=30, cool_lo=12)
CAP = V('#e06a1c', 6, spread=0.34, warm_hi=12, shadow_hue=25, cool_lo=10, hi_desat=0.85)
REFL = V('#e6e2da', 4, spread=0.16, warm_hi=4, shadow_hue=260, cool_lo=6)
stake = np.zeros((S, S), bool)
stake[0:2, 0:4] = True
stake[:, 0:2] = True
st_idx = np.where(xx == 0, 3, 2) + (white(51) > .75) - (white(52) > .8)
st_idx[0, 0:4] = 4
st_idx[1, 2:4] = 1
cap = np.zeros((S, S), bool)
cap[0:7, 8:11] = True
cap_idx = np.where(xx == 8, 4, np.where(xx == 10, 2, 3)) + (white(53) > .8)
cap_idx[0, 8:11] = 5
refl = np.zeros((S, S), bool)
refl[1:3, 8:11] = True
rf_idx = np.where(yy == 1, 3, 1) - (xx == 10)
B('barrier_post', composite((STAKE, np.clip(st_idx, 0, 5), stake), (CAP, np.clip(cap_idx, 0, 5), cap), (REFL, np.clip(rf_idx, 0, 3), refl)))

# --- cloth barrier tape: rows 6-9, red/white diagonal stripes, lit top row, dark bottom row
RED = V('#b8352c', 5, spread=0.28, warm_hi=8, shadow_hue=20, cool_lo=8)
WHITE = V('#cfccc3', 5, spread=0.18, warm_hi=4, shadow_hue=260, cool_lo=6)
tape = (yy >= 6) & (yy <= 9)
stripe = ((xx + (9 - yy)) // 3) % 2 == 0
t_idx = np.where(yy == 6, 3, np.where(yy == 9, 1, 2)) + (white(57) > .82)
B('cloth_barrier', composite((RED, np.clip(t_idx, 0, 4), tape & stripe), (WHITE, np.clip(t_idx, 0, 4), tape & ~stripe)))

# --- workshop stand materials (small model parts: smooth, a couple of sheen strokes, no bevel)
def metal(base, seed, n=7, spread=0.24, **kw):
    r = V(base, n, spread=spread, **kw)
    f = 0.75 * noise(seed, cells=(1, 4), octaves=2) + 0.25 * noise(seed + 1, cells=(8, 8), octaves=1)
    idx = quantize(f, gauss_weights(n, .5, .16))
    for y, x in ((3, 4), (4, 5), (10, 10), (11, 11)):
        idx[y, x] += 2
    return r.paint(np.clip(idx, 0, n - 1))


B('stand_brass', metal('#c08a40', 111, spread=0.30, warm_hi=18, shadow_hue=25, cool_lo=18, hi_desat=1.0))
B('stand_metal', metal('#3a454c', 112, spread=0.20, warm_hi=3, shadow_hue=260, cool_lo=10))
B('stand_rubber', metal('#25272a', 113, spread=0.10, warm_hi=1, shadow_hue=260, cool_lo=4))


# ======================================================================= items
def iso_icon(top, side, height=1.0):
    """16x16 isometric block icon from block textures (top 100 %, left 80 %, right 62 %)."""
    out = np.zeros((S, S, 4), np.uint8)
    for y in range(S):
        for x in range(S):
            px, py = x + .5, y + .5
            sx = (px - 8) / 7.5
            col = None
            # top face at height h
            yt = py - (1 - height) * 8
            u, w = (sx + yt / 3.75) / 2, (yt / 3.75 - sx) / 2
            if 0 <= u < 1 and 0 <= w < 1:
                col = top[int(w * 16), int(u * 16)].astype(float)
            else:
                if sx <= 0:  # front-left face, w = 1
                    u = sx + 1
                    h = height - (py - 3.75 * (u + 1) - (1 - height) * 8) / 8
                    if 0 <= u < 1 and 0 <= h < height:
                        col = side[min(15, int((1 - h) * 16)), min(15, int(u * 16))].astype(float) * [.8, .8, .8, 1]
                else:        # front-right face, u = 1
                    w = 1 - sx
                    h = height - (py - 3.75 * (1 + w) - (1 - height) * 8) / 8
                    if 0 <= w < 1 and 0 <= h < height:
                        col = side[min(15, int((1 - h) * 16)), min(15, int((1 - w) * 16))].astype(float) * [.62, .62, .62, 1]
            if col is not None and col[3] > 0:
                out[y, x] = np.clip(col, 0, 255)
    return out


I('trail_dirt', iso_icon(BLOCKS['packed_trail_dirt_top'], BLOCKS['packed_trail_dirt_side']))
I('airbag', iso_icon(BLOCKS['airbag'], BLOCKS['airbag'], height=.75))



def part(art, ramp, **kw):
    """ASCII silhouette: '#' body (auto-shaded, outline on the rim), '*' brightest, '-' dark accent.
    '+' is plain body too (a fill of '+' would be a flat highlight - the 'flat fills' anti-pattern)."""
    m, ch = mask_from_ascii(art.replace('+', '#'))
    return ramp, shade_item(m, len(ramp), ch, **kw), m


def line(art, ramp, v):
    """1 px detail strokes (map trails, screen trace) at one shade - no outline."""
    m, _ = mask_from_ascii(art)
    return ramp, np.where(m, v, 0), m


R_STONE = item_ramp('#8a8e90', 8, spread=0.42, warm_hi=5, shadow_hue=260, cool_lo=10)
R_MOSS = item_ramp('#5e7a33', 6, spread=0.36, warm_hi=10, shadow_hue=150, cool_lo=10)
R_WOOD = item_ramp('#9a7547', 7, spread=0.42, warm_hi=8, shadow_hue=25, cool_lo=12)
R_ROOT = item_ramp('#6e4b2d', 7, spread=0.42, warm_hi=10, shadow_hue=25, cool_lo=12)
R_STEEL = item_ramp('#a9b1b7', 8, spread=0.45, mid_bias=-0.05, warm_hi=4, shadow_hue=250, cool_lo=14, hi_desat=0.5)
R_DARK = item_ramp('#3b4248', 7, spread=0.30, warm_hi=3, shadow_hue=260, cool_lo=10)
R_RED = item_ramp('#c0392f', 6, spread=0.36, warm_hi=8, shadow_hue=20, cool_lo=8)
R_WHITE = item_ramp('#d2cfc6', 6, spread=0.26, warm_hi=4, shadow_hue=260, cool_lo=6)
R_YELLOW = item_ramp('#e0b23a', 6, spread=0.38, warm_hi=10, shadow_hue=30, cool_lo=10, hi_desat=0.9)
R_ORANGE = item_ramp('#e07b25', 6, spread=0.36, warm_hi=12, shadow_hue=25, cool_lo=10)
R_PAPER = item_ramp('#e3d8b4', 6, spread=0.22, warm_hi=6, shadow_hue=40, cool_lo=8)
R_SCREEN = item_ramp('#7fc58a', 5, spread=0.30, warm_hi=6, shadow_hue=170, cool_lo=8)
R_FILM = item_ramp('#a9d7e6', 6, spread=0.30, warm_hi=4, shadow_hue=230, cool_lo=8, hi_desat=0.7)

I('trail_deck', composite(part("""
................
................
................
................
.........######.
.......##*####-#
.....##*####-###
...##*####-##*-#
..#*####-##*####
..#*##-##*####-#
..#-##*####-##..
..##*####-##....
..#####-##......
...#####........
""", item_ramp('#8f6a3f', 7, spread=0.42, warm_hi=8, shadow_hue=25, cool_lo=12))))

# rock lump with moss on top
I('trail_rock', composite(part("""
................
................
................
.....####.......
....#*++##......
...#*+++++##....
..#*+++++++##...
..#++++++++++#..
.#+++++++++++#..
.#+++++++++-+#..
.#++++++++--+#..
..#+++++----##..
..##------###...
....#######.....
""", R_STONE), part("""
................
................
................
.....####.......
....#*++##......
...#*+.+++##....
..#*+.......#...
""", R_MOSS)))

# tangle of roots
I('trail_roots', composite(part("""
................
................
.........##.....
........#*+#....
..##...#*+#.....
.#*+#.#*+#......
..#*+#*+#..##...
...#*++####*+#..
....#++++++++#..
...#+-##+-##-#..
..#+-#..#+#.##..
.#+-#....#+#....
.#-#......#-#...
..#........#....
""", R_ROOT)))

# post with two steel bands
I('wood_support', composite(part("""
......####......
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
......####......
""", R_WOOD), part("""
................
................
................
....########....
....#*++++-#....
....########....
................
................
................
................
....########....
....#*++++-#....
....########....
""", R_STEEL)))

# sign on a post: board with two painted arrows, post right under it
I('trail_sign', composite(part("""
................
................
................
................
................
................
................
................
................
................
.......##.......
.......#*#......
.......#*#......
.......#-#......
.......#-#......
.......###......
""", R_WOOD), part("""
................
................
.##############.
.#*###########-#
.#*###########-#
.#*###########-#
.#*###########-#
.#*###########-#
.#*###########-#
.#------------##
.##############.
""", R_WOOD), line("""
................
................
................
................
....#...........
...#######......
....#...........
.........#......
....######......
.........#......
""", R_WHITE, 4)))

# trail shovel: only the steel spade + socket; the item model puts it on top of vanilla's own stick
# (layer0 = minecraft:item/stick), so the handle is the real Minecraft stick from the player's game.
along, across = xx - yy, xx + yy - 15
half = np.where(along < 9.5, 2.6, np.sqrt(np.clip(2.9 ** 2 - (along - 9.5) ** 2 * 0.9, 0, None)))
blade = (along >= 4.5) & (along <= 12.6) & (np.abs(across) <= half)
socket = (along >= 2.5) & (along < 4.5) & (np.abs(across) <= 1.1)
sp_idx = shade_item(blade, len(R_STEEL))
sp_idx[blade & (np.abs(across) < .6) & (along > 6) & (along < 12) & (sp_idx > 0)] = len(R_STEEL) - 2   # pressed ridge
sk_idx = np.where(across < 0, 3, 1) * socket
I('trail_shovel', composite((R_DARK, sk_idx, socket), (R_STEEL, sp_idx, blade)))

# floor pump: yellow barrel, T-handle, base plate, hose
I('bike_pump', composite(part("""
................
................
................
................
................
.....######.....
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
.....#*++-#.....
.....######.....
""", R_YELLOW), part("""
...##########...
...#*+++++++#...
...##########...
.......##.......
.......##.......
................
................
................
................
................
................
................
................
................
................
..############..
..#*++++++++-#..
..############..
""", R_DARK), part("""
................
................
................
................
................
................
................
................
..........##....
...........#+#..
............#+#.
............#-#.
...........#-#..
..........##....
""", R_DARK)))

# roll of red/white tape
roll = disc(S, 8, 8, 6.6) & ~disc(S, 8, 8, 2.4)
r_idx = shade_item(roll, len(R_RED))
stripe = ((np.arctan2(yy + .5 - 8, xx + .5 - 8) + np.pi) / (2 * np.pi) * 10).astype(int) % 2 == 0
wm = roll & stripe & (r_idx > 0)
w_idx = shade_item(roll, len(R_WHITE))
core = ring(S, 8, 8, 2.4, 1.4)
I('cloth_barrier', composite((R_RED, r_idx, roll), (R_WHITE, w_idx, wm), (R_DARK, np.where(yy < 8, 2, 4), core)))


# handheld GPS: dark body, stub antenna, green screen with a red trace, two keys
I('trail_gps', composite(part("""
....##..........
....#*#.........
....#*#.........
....###.........
...###########..
...#*########-#.
...#*#######-#..
...#*#.....#-#..
...#*#.....#-#..
...#*#.....#-#..
...#*#######-#..
...#*########-#.
...#*#######--#.
...#*########-#.
...#---------##.
...###########..
""", R_DARK), part("""
................
................
................
................
................
................
................
.....*####-.....
.....#####-.....
.....####--.....
""", R_SCREEN), line("""
................
................
................
................
................
................
................
.........#......
.......##.......
......#.........
""", R_RED, 4), line("""
................
................
................
................
................
................
................
................
................
................
................
................
.....*...*......
""", R_STEEL, 6)))

# folded trail map: paper panels with coloured trails
I('trail_map', composite(part("""
................
................
.##############.
.#*++++#*+++++-#
.#+++++#++++++-#
.#+++++#++++++-#
.#+++++#++++++-#
.#+++++#++++++-#
.#+++++#++++++-#
.#+++++#++++++-#
.#+++++#++++++-#
.#+++++#++++++-#
.#-----#------##
.##############.
""", R_PAPER), line("""
................
................
................
................
............#...
...........#....
......###.#.....
.....#...#......
....#...........
...#............
""", R_RED, 3), line("""
................
................
................
................
................
................
................
...........#....
..........#.....
.........#......
........##......
.......#........
""", item_ramp('#3a7bd5', 5, spread=0.3), 3), line("""
................
................
................
....#...........
.....#..........
......#.........
""", item_ramp('#3e9b45', 5, spread=0.3), 3)))


# ======================================================================= output
for name, img in BLOCKS.items():
    save(img, os.path.join(OUT, 'block', name + '.png'))
for name, img in ITEMS.items():
    save(img, os.path.join(OUT, 'item', name + '.png'))
print('wrote', len(BLOCKS), 'blocks and', len(ITEMS), 'items to', OUT)
