package com.descentmtb.client.model;

import com.descentmtb.custom.BikeParts.FrameShape;

/** Generated by tools/gen_frame_catalog.py; edit tools/frame_profiles.json. */
final class FrameLayouts {
    private static final EnduroLinkage N = new EnduroLinkage(true, new EnduroLinkage.Point(-6.6000f, 3.2800f), new EnduroLinkage.Point(-7.6000f, 4.7500f), new EnduroLinkage.Point(-9.6000f, 5.8000f), new EnduroLinkage.Point(-10.8000f, 4.2884f), new EnduroLinkage.Point(-7.7000f, 1.2000f), new EnduroLinkage.Point(-7.6000f, 4.0000f));
    private static final EnduroLinkage T = new EnduroLinkage(false, new EnduroLinkage.Point(-8.3000f, 4.2000f), new EnduroLinkage.Point(-5.8500f, 9.2000f), new EnduroLinkage.Point(-10.6500f, 5.8000f), new EnduroLinkage.Point(-11.2000f, 4.3840f), new EnduroLinkage.Point(-13.6000f, -0.3000f), new EnduroLinkage.Point(-10.7000f, 3.6500f));
    private static final EnduroLinkage U = new EnduroLinkage(false, new EnduroLinkage.Point(-8.3000f, 4.2000f), new EnduroLinkage.Point(-5.8000f, 9.1500f), new EnduroLinkage.Point(-10.3500f, 5.8000f), new EnduroLinkage.Point(-10.9000f, 4.3120f), new EnduroLinkage.Point(-11.7000f, -1.2000f), new EnduroLinkage.Point(-9.6000f, 3.6500f));
    private static final EnduroLinkage M = new EnduroLinkage(true, new EnduroLinkage.Point(-6.4000f, 3.2320f), new EnduroLinkage.Point(-7.0000f, 4.7000f), new EnduroLinkage.Point(-8.7000f, 5.7000f), new EnduroLinkage.Point(-10.7000f, 4.2640f), new EnduroLinkage.Point(-9.7000f, 0.3000f), new EnduroLinkage.Point(-7.5000f, 4.0000f));
    private static final EnduroLinkage G = new EnduroLinkage(false, new EnduroLinkage.Point(-8.3000f, 4.2000f), new EnduroLinkage.Point(-5.9000f, 9.1500f), new EnduroLinkage.Point(-10.7000f, 5.8500f), new EnduroLinkage.Point(-11.3000f, 4.4080f), new EnduroLinkage.Point(-12.7000f, -0.2000f), new EnduroLinkage.Point(-10.3000f, 3.6500f));
    private static final EnduroLinkage J = new EnduroLinkage(false, new EnduroLinkage.Point(-8.3000f, 4.2000f), new EnduroLinkage.Point(-5.8500f, 9.2000f), new EnduroLinkage.Point(-11.2500f, 5.8000f), new EnduroLinkage.Point(-10.9000f, 4.3120f), new EnduroLinkage.Point(-13.4000f, 0.1500f), new EnduroLinkage.Point(-11.1000f, 3.6000f));
    static EnduroLinkage forShape(FrameShape shape) {
        return switch (shape) {
            case SANTA_CRUZ_NOMAD -> N;
            case CANYON_TORQUE -> T;
            case CUBE_STEREO_ONE77 -> U;
            case COMMENCAL_META_SX -> M;
            case YT_CAPRA -> G;
            case SPECIALIZED_STUMPJUMPER -> J;
            default -> null;
        };
    }
    private FrameLayouts() {}
}
