package com.descentmtb.client.model;

import com.descentmtb.DescentMtb;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import java.util.function.ToIntFunction;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.resources.ResourceLocation;
import org.joml.Vector3f;

/**
 * 125 cc pit bike (Kayo / CRF125 style): steel backbone frame with a low horizontal finned cylinder, header running
 * under the engine to a small muffler on the right, small tank and shrouds, short seat, front number plate, small
 * fenders, short upside-down fork with gold stanchions, monoshock, 14"/12" spoked wheels on knobby tyres.
 *
 * <p>Built at 32 model units per metre (twice the bicycles' texel density) and drawn at half scale; see
 * {@link MotoModel} for the conventions and the per-group paint.
 *
 * <pre>
 * root
 *  |- frame            frame, engine, exhaust, bodywork, seat, pegs, shock
 *  |   |- steer_axis   head tube centre, xRot = -25 deg (rake)
 *  |   |   `- steer    yRot = steering
 *  |   |       |- fork_upper   triple clamps, outer fork tubes, bars, levers, front fender, number plate
 *  |   |       `- fork_lower   gold inner tubes and axle lugs; local y slides up the axis (fork travel)
 *  |   |           `- front_wheel   xRot = spin
 *  |   `- swingarm     pivot, xRot = swing (rear travel); arms, chain, rear caliper
 *  |       `- rear_wheel   xRot = spin
 * </pre>
 *
 * <p>The cube table and the texture are generated by {@code python tools/gen_dirt_bike.py} (geometry in metres,
 * UV packing, hand-shaded painting, preview renders in {@code tools/preview/pit_bike}); edit the script, not the
 * table.
 */
public class PitBikeModel extends MotoModel {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(
            ResourceLocation.fromNamespaceAndPath(DescentMtb.MODID, "pit_bike"), "main");
    public static final ResourceLocation TEXTURE =
            ResourceLocation.fromNamespaceAndPath(DescentMtb.MODID, "textures/entity/pit_bike.png");

    public static final float FORK_TRAVEL_M = 0.16f, REAR_TRAVEL_M = 0.15f;

    /** Rider anchors in metres, Y up, -Z forward, +X = rider's left, origin on the ground between the axles. */
    public static final Vector3f GRIP_LEFT = new Vector3f(0.33f, 0.86f, -0.28f);
    public static final Vector3f FOOTPEG_LEFT = new Vector3f(0.15f, 0.27f, 0.04f);
    /** Steering axis in bicycle model pixels (16 per metre, Y down) for the grip maths: head tube centre and the
     *  unit direction down the axis (25 deg rake). */
    public static final Vector3f STEER_PIVOT_PX = new Vector3f(0f, -12.48f, -4.8f);
    public static final Vector3f STEER_AXIS_DOWN = new Vector3f(0f, (float) Math.cos(Math.toRadians(25)), (float) -Math.sin(Math.toRadians(25)));

    public PitBikeModel(ModelPart root) {
        // rear axle relative to the swingarm pivot at rest: 0.05 m down, 0.46 m back
        super(root, GROUP_CUBES, FORK_TRAVEL_M, REAR_TRAVEL_M, 0.33f - 0.28f, 0.56f - 0.10f);
    }

    @Override
    public ResourceLocation texture() {
        return TEXTURE;
    }

    /** Fork compression 0..0.16 m, rear wheel travel 0..0.15 m; see {@link MotoModel#setupPose}. */
    @Override
    public void setupPose(float steerRad, float forkTravelM, float rearTravelM, float frontSpin, float rearSpin) {
        applyPose(steerRad, forkTravelM, rearTravelM, frontSpin, rearSpin);
    }

    @Override
    public void renderPainted(PoseStack pose, VertexConsumer vc, int light, int overlay, ToIntFunction<String> color) {
        drawPainted(pose, vc, light, overlay, -1, color);
    }

    // ------------------------------------------------------------------ group table and geometry (generated)
    // <GROUPS>
    private static final String[][] GROUP_CUBES = {
        // plastic
        {"frame/tank", "frame/shroud_l", "frame/shroud_scoop_l", "frame/airbox_cover_l", "frame/shroud_r",
         "frame/shroud_scoop_r", "frame/airbox_cover_r"},
        // fender
        {"frame/side_plate_l", "frame/side_plate_r", "frame/rear_fender", "frame/rear_fender_tip",
         "frame/steer_axis/steer/fork_upper/front_plate", "frame/steer_axis/steer/fork_lower/front_fender",
         "frame/steer_axis/steer/fork_lower/front_fender_tip",
         "frame/steer_axis/steer/fork_lower/front_fender_rear"},
        // frame
        {"frame/spar_l", "frame/spar_drop_l", "frame/cradle_l", "frame/subframe_l", "frame/subframe_strut_l",
         "frame/pivot_plate_l", "frame/spar_r", "frame/spar_drop_r", "frame/cradle_r", "frame/subframe_r",
         "frame/subframe_strut_r", "frame/pivot_plate_r", "frame/down_tube", "frame/head_tube",
         "frame/head_gusset", "frame/peg_mount_l", "frame/peg_mount_r", "frame/skid_plate",
         "frame/steer_axis/steer/fork_lower/fender_stay_l", "frame/steer_axis/steer/fork_lower/fender_stay_r",
         "frame/swingarm/linkage"},
        // seat
        {"frame/seat", "frame/seat_front"},
        // rim
        {"frame/steer_axis/steer/fork_lower/front_wheel/f_rim0",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim1",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim2",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim3",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim4",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim5",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim6",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim7",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim8",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim9",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim10",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim11",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim12",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim13",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim14",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim15",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim16",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim17",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim18",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim19",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim20",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim21",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim22",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim23",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim24",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim25",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim26",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_rim27", "frame/swingarm/rear_wheel/r_rim0",
         "frame/swingarm/rear_wheel/r_rim1", "frame/swingarm/rear_wheel/r_rim2",
         "frame/swingarm/rear_wheel/r_rim3", "frame/swingarm/rear_wheel/r_rim4",
         "frame/swingarm/rear_wheel/r_rim5", "frame/swingarm/rear_wheel/r_rim6",
         "frame/swingarm/rear_wheel/r_rim7", "frame/swingarm/rear_wheel/r_rim8",
         "frame/swingarm/rear_wheel/r_rim9", "frame/swingarm/rear_wheel/r_rim10",
         "frame/swingarm/rear_wheel/r_rim11", "frame/swingarm/rear_wheel/r_rim12",
         "frame/swingarm/rear_wheel/r_rim13", "frame/swingarm/rear_wheel/r_rim14",
         "frame/swingarm/rear_wheel/r_rim15", "frame/swingarm/rear_wheel/r_rim16",
         "frame/swingarm/rear_wheel/r_rim17", "frame/swingarm/rear_wheel/r_rim18",
         "frame/swingarm/rear_wheel/r_rim19", "frame/swingarm/rear_wheel/r_rim20",
         "frame/swingarm/rear_wheel/r_rim21", "frame/swingarm/rear_wheel/r_rim22",
         "frame/swingarm/rear_wheel/r_rim23", "frame/swingarm/rear_wheel/r_rim24",
         "frame/swingarm/rear_wheel/r_rim25", "frame/swingarm/rear_wheel/r_rim26",
         "frame/swingarm/rear_wheel/r_rim27"},
        // spring
        {"frame/shock_spring"},
        // anodized
        {"frame/ignition_cover", "frame/head_cap", "frame/countershaft",
         "frame/steer_axis/steer/fork_upper/top_clamp", "frame/steer_axis/steer/fork_upper/lower_clamp",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_hub",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_hub_l",
         "frame/steer_axis/steer/fork_lower/front_wheel/f_hub_r", "frame/swingarm/rear_wheel/r_hub",
         "frame/swingarm/rear_wheel/r_hub_l", "frame/swingarm/rear_wheel/r_hub_r",
         "frame/swingarm/rear_wheel/r_sprocket0", "frame/swingarm/rear_wheel/r_sprocket1",
         "frame/swingarm/rear_wheel/r_sprocket2", "frame/swingarm/rear_wheel/r_sprocket3",
         "frame/swingarm/rear_wheel/r_sprocket4", "frame/swingarm/rear_wheel/r_sprocket5"},
    };
    // </GROUPS>

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        // <GENERATED>
        PartDefinition frame = bone(root, "frame", 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f);
        cube(frame, "spar_l", 194, 19, 1.6920f, -22.0000f, -4.8800f, 1.0240f, 1.2800f, 9.0225f, -19.6902f, 3.4013f, 0.0000f);
        cube(frame, "spar_drop_l", 141, 34, 2.1960f, -16.6400f, 1.2800f, 0.9600f, 0.9600f, 8.6013f, -63.2387f, 7.4773f, 0.0000f);
        cube(frame, "cradle_l", 216, 19, 1.8000f, -8.5600f, -1.6800f, 0.9600f, 0.9600f, 9.0985f, -13.2152f, 6.5345f, 0.0000f);
        cube(frame, "subframe_l", 72, 0, 1.7640f, -19.3600f, 8.0000f, 0.8000f, 0.8000f, 16.0072f, -1.1455f, -1.2889f, 0.0000f);
        cube(frame, "subframe_strut_l", 75, 19, 2.0160f, -15.8400f, 8.8000f, 0.6400f, 0.6400f, 12.2158f, 29.8489f, -4.6774f, 0.0000f);
        cube(frame, "pivot_plate_l", 238, 19, 2.4480f, -11.5200f, 3.2000f, 0.6400f, 8.3200f, 2.2400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "spar_r", 0, 34, -1.6920f, -22.0000f, -4.8800f, 1.0240f, 1.2800f, 9.0225f, -19.6902f, -3.4013f, 0.0000f);
        cube(frame, "spar_drop_r", 162, 34, -2.1960f, -16.6400f, 1.2800f, 0.9600f, 0.9600f, 8.6013f, -63.2387f, -7.4773f, 0.0000f);
        cube(frame, "cradle_r", 22, 34, -1.8000f, -8.5600f, -1.6800f, 0.9600f, 0.9600f, 9.0985f, -13.2152f, -6.5345f, 0.0000f);
        cube(frame, "subframe_r", 107, 0, -1.7640f, -19.3600f, 8.0000f, 0.8000f, 0.8000f, 16.0072f, -1.1455f, 1.2889f, 0.0000f);
        cube(frame, "subframe_strut_r", 102, 19, -2.0160f, -15.8400f, 8.8000f, 0.6400f, 0.6400f, 12.2158f, 29.8489f, 4.6774f, 0.0000f);
        cube(frame, "pivot_plate_r", 44, 34, -2.4480f, -11.5200f, 3.2000f, 0.6400f, 8.3200f, 2.2400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "down_tube", 142, 0, 0.0000f, -16.4800f, -7.9200f, 1.2800f, 1.2800f, 13.6263f, -74.3318f, -0.0000f, 0.0000f);
        cube(frame, "head_tube", 202, 56, 0.0000f, -24.9600f, -9.6000f, 1.6000f, 3.2000f, 1.6000f, -25.0000f, -0.0000f, 0.0000f);
        cube(frame, "head_gusset", 210, 56, 0.0000f, -23.5200f, -8.3200f, 1.4400f, 1.6000f, 2.5600f, -20.0000f, -0.0000f, 0.0000f);
        cube(frame, "pivot_bolt", 240, 105, 0.0000f, -10.5600f, 3.2000f, 6.0800f, 0.8000f, 0.8000f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "crankcase", 129, 19, 0.0000f, -10.5600f, -0.6400f, 5.4400f, 6.4000f, 6.4000f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "case_cover_l", 51, 34, 3.0400f, -10.5600f, 0.0000f, 0.6400f, 4.8000f, 5.4400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "case_cover_r", 95, 46, -3.0400f, -10.8800f, -1.2800f, 0.6400f, 3.8400f, 3.8400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "clutch_cover", 115, 56, -3.4560f, -10.7200f, -1.2800f, 0.5120f, 2.5600f, 2.5600f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "ignition_cover", 219, 56, 3.4560f, -11.8400f, -2.2400f, 0.3840f, 2.0800f, 2.0800f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "sump", 223, 46, 0.0000f, -7.5200f, -0.3200f, 3.8400f, 1.2800f, 5.4400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "fin0", 225, 56, 0.0000f, -12.4311f, -4.3103f, 4.0000f, 0.3840f, 4.0000f, 80.0000f, -0.0000f, 0.0000f);
        cube(frame, "fin1", 0, 64, 0.0000f, -12.5478f, -4.9721f, 3.8720f, 0.3840f, 3.8720f, 80.0000f, -0.0000f, 0.0000f);
        cube(frame, "fin2", 17, 64, 0.0000f, -12.6645f, -5.6339f, 3.7440f, 0.3840f, 3.7440f, 80.0000f, -0.0000f, 0.0000f);
        cube(frame, "fin3", 174, 76, 0.0000f, -12.7812f, -6.2956f, 3.6160f, 0.3840f, 3.6160f, 80.0000f, -0.0000f, 0.0000f);
        cube(frame, "fin4", 190, 76, 0.0000f, -12.8979f, -6.9574f, 3.4880f, 0.3840f, 3.4880f, 80.0000f, -0.0000f, 0.0000f);
        cube(frame, "cylinder", 123, 56, 0.0000f, -12.6534f, -5.5708f, 2.7200f, 3.2000f, 2.7200f, 80.0000f, -0.0000f, 0.0000f);
        cube(frame, "head", 33, 64, 0.0000f, -13.0146f, -7.6192f, 3.3600f, 1.6000f, 3.3600f, 80.0000f, -0.0000f, 0.0000f);
        cube(frame, "head_cap", 233, 92, 0.0000f, -13.1813f, -8.5646f, 2.2400f, 0.3840f, 2.2400f, 80.0000f, -0.0000f, 0.0000f);
        cube(frame, "spark_cap", 0, 109, 0.0000f, -15.1224f, -7.7768f, 0.8000f, 1.1200f, 0.8000f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "carb", 205, 76, 0.0000f, -14.4000f, -1.4400f, 1.6000f, 1.7600f, 2.2400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "airbox", 225, 34, 0.0000f, -18.0800f, 9.6000f, 3.8400f, 3.2000f, 5.4400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "airbox_hose", 0, 46, 0.0000f, -16.3200f, 4.4800f, 1.2800f, 1.2800f, 7.0400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "countershaft", 214, 76, 3.4560f, -9.6000f, 0.9600f, 0.4480f, 1.6000f, 1.6000f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "kick_lever", 48, 64, -3.8400f, -8.9600f, 1.9200f, 0.3840f, 0.8000f, 3.8400f, 35.0000f, -0.0000f, 0.0000f);
        cube(frame, "shift_lever", 220, 76, 4.0000f, -8.3200f, 0.9600f, 0.3840f, 0.5120f, 2.8800f, -8.0000f, -0.0000f, 0.0000f);
        cube(frame, "brake_pedal", 228, 76, -4.1600f, -8.4800f, 0.0000f, 0.3840f, 0.5120f, 3.2000f, -8.0000f, -0.0000f, 0.0000f);
        cube(frame, "header0", 243, 92, -1.9200f, -12.4000f, -7.8400f, 0.9600f, 0.9600f, 1.9530f, -34.9920f, -90.0000f, 0.0000f);
        cube(frame, "header1", 58, 64, -3.0400f, -10.2400f, -7.1200f, 0.9600f, 0.9600f, 3.5670f, -63.7824f, -23.9625f, 0.0000f);
        cube(frame, "header2", 69, 64, -3.5200f, -7.7600f, -4.8000f, 0.9600f, 0.9600f, 3.6661f, -28.6906f, -5.7106f, 0.0000f);
        cube(frame, "header3", 135, 56, -3.7600f, -6.8800f, -0.9600f, 0.9600f, 0.9600f, 4.4829f, 0.0000f, -2.0454f, 0.0000f);
        cube(frame, "header4", 80, 64, -4.0800f, -8.2400f, 2.7200f, 0.9600f, 0.9600f, 3.9904f, 42.9718f, -9.4623f, 0.0000f);
        cube(frame, "muffler", 154, 19, -4.4800f, -11.6800f, 8.9600f, 1.9200f, 2.0800f, 10.4675f, 23.4171f, -1.9092f, 0.0000f);
        cube(frame, "muffler_cap", 237, 76, -4.6560f, -14.0000f, 14.3200f, 1.6640f, 1.7920f, 1.2189f, 23.1901f, -1.6366f, 0.0000f);
        cube(frame, "muffler_tip", 5, 109, -4.6880f, -14.3520f, 15.2000f, 0.7680f, 0.7680f, 0.6788f, 19.2678f, -2.8624f, 0.0000f);
        cube(frame, "muffler_band", 0, 97, -4.4800f, -11.5200f, 8.9600f, 2.0800f, 2.2400f, 0.4480f, 20.0000f, -0.0000f, 0.0000f);
        cube(frame, "tank", 65, 34, 0.0000f, -24.1600f, -4.6400f, 5.4400f, 3.3600f, 7.0400f, 6.0000f, -0.0000f, 0.0000f);
        cube(frame, "tank_stripe", 0, 56, 0.0000f, -25.9581f, -4.8290f, 0.8000f, 0.1920f, 6.4000f, 6.0000f, -0.0000f, 0.0000f);
        cube(frame, "tank_cap", 9, 109, 0.0000f, -25.9840f, -5.1200f, 1.4400f, 0.4480f, 1.4400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "shroud_l", 91, 34, 3.1360f, -23.2000f, -4.6400f, 0.7040f, 4.4800f, 6.4000f, 6.0000f, -0.0000f, -4.0000f);
        cube(frame, "shroud_stripe_l_w", 105, 46, 3.1360f, -23.2000f, -4.6400f, 0.9600f, 0.9600f, 6.0800f, 36.0000f, -0.0000f, -4.0000f);
        cube(frame, "shroud_stripe_l_k", 16, 56, 3.1766f, -22.6189f, -4.2168f, 0.9600f, 0.4800f, 6.0800f, 36.0000f, -0.0000f, -4.0000f);
        cube(frame, "shroud_scoop_l", 244, 76, 3.2000f, -24.9600f, -8.1600f, 0.6400f, 1.9200f, 1.6000f, 30.0000f, -0.0000f, -4.0000f);
        cube(frame, "side_plate_l", 18, 46, 3.2000f, -18.7200f, 14.0800f, 0.5120f, 3.8400f, 5.1200f, -6.0000f, -0.0000f, 0.0000f);
        cube(frame, "airbox_cover_l", 31, 46, 2.3040f, -18.2400f, 9.6000f, 0.5120f, 3.5200f, 5.4400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "peg_l", 7, 97, 4.8000f, -8.6400f, 1.2800f, 2.5600f, 0.6400f, 1.4400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "peg_tooth_l0", 16, 109, 4.0000f, -9.0880f, 1.2800f, 0.2240f, 0.3200f, 1.4400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "peg_tooth_l1", 21, 109, 4.6400f, -9.0880f, 1.2800f, 0.2240f, 0.3200f, 1.4400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "peg_tooth_l2", 26, 109, 5.2800f, -9.0880f, 1.2800f, 0.2240f, 0.3200f, 1.4400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "peg_mount_l", 16, 97, 3.0400f, -8.6400f, 1.2800f, 1.2800f, 1.2800f, 1.2800f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "shroud_r", 107, 34, -3.1360f, -23.2000f, -4.6400f, 0.7040f, 4.4800f, 6.4000f, 6.0000f, -0.0000f, 4.0000f);
        cube(frame, "shroud_stripe_r_w", 121, 46, -3.1360f, -23.2000f, -4.6400f, 0.9600f, 0.9600f, 6.0800f, 36.0000f, -0.0000f, 4.0000f);
        cube(frame, "shroud_stripe_r_k", 32, 56, -3.1766f, -22.6189f, -4.2168f, 0.9600f, 0.4800f, 6.0800f, 36.0000f, -0.0000f, 4.0000f);
        cube(frame, "shroud_scoop_r", 250, 76, -3.2000f, -24.9600f, -8.1600f, 0.6400f, 1.9200f, 1.6000f, 30.0000f, -0.0000f, 4.0000f);
        cube(frame, "side_plate_r", 44, 46, -3.2000f, -18.7200f, 14.0800f, 0.5120f, 3.8400f, 5.1200f, -6.0000f, -0.0000f, 0.0000f);
        cube(frame, "airbox_cover_r", 57, 46, -2.3040f, -18.2400f, 9.6000f, 0.5120f, 3.5200f, 5.4400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "peg_r", 23, 97, -4.8000f, -8.6400f, 1.2800f, 2.5600f, 0.6400f, 1.4400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "peg_tooth_r0", 31, 109, -4.0000f, -9.0880f, 1.2800f, 0.2240f, 0.3200f, 1.4400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "peg_tooth_r1", 36, 109, -4.6400f, -9.0880f, 1.2800f, 0.2240f, 0.3200f, 1.4400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "peg_tooth_r2", 41, 109, -5.2800f, -9.0880f, 1.2800f, 0.2240f, 0.3200f, 1.4400f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "peg_mount_r", 32, 97, -3.0400f, -8.6400f, 1.2800f, 1.2800f, 1.2800f, 1.2800f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "seat", 0, 19, 0.0000f, -21.6000f, 6.7200f, 6.0800f, 1.7600f, 11.5200f, -1.5000f, -0.0000f, 0.0000f);
        cube(frame, "seat_front", 91, 64, 0.0000f, -21.4400f, 0.0000f, 4.8000f, 1.6000f, 2.5600f, 10.0000f, -0.0000f, 0.0000f);
        cube(frame, "seat_base", 37, 19, 0.0000f, -20.4800f, 6.7200f, 5.4400f, 0.8000f, 12.8000f, -1.5000f, -0.0000f, 0.0000f);
        cube(frame, "rear_fender", 70, 46, 0.0000f, -20.0000f, 19.8400f, 3.2000f, 0.4480f, 8.3200f, 6.0000f, -0.0000f, 0.0000f);
        cube(frame, "rear_fender_tip", 39, 97, 0.0000f, -20.0000f, 24.8000f, 2.5600f, 0.4480f, 2.2400f, 26.0000f, -0.0000f, 0.0000f);
        cube(frame, "shock_body", 147, 56, 0.0000f, -14.0000f, 5.4400f, 1.0240f, 1.0240f, 4.1998f, -107.7447f, 0.0000f, 180.0000f);
        cube(frame, "shock_spring", 159, 56, 0.0000f, -17.7600f, 4.2400f, 1.7600f, 1.7600f, 3.6939f, -107.6501f, 0.0000f, 180.0000f);
        cube(frame, "shock_mount", 46, 109, 0.0000f, -19.6800f, 3.5200f, 1.6000f, 0.5120f, 0.5120f, 0.0000f, -0.0000f, 0.0000f);
        cube(frame, "skid_plate", 137, 46, 0.0000f, -6.5600f, -2.2400f, 4.1600f, 0.3200f, 7.0400f, 0.0000f, -0.0000f, 0.0000f);
        PartDefinition steer_axis = bone(frame, "steer_axis", 0.0000f, -24.9600f, -9.6000f, -25.0000f, -0.0000f, 0.0000f);
        PartDefinition steer = bone(steer_axis, "steer", 0.0000f, 0.0000f, 0.0000f, -0.0000f, -0.0000f, 0.0000f);
        PartDefinition fork_upper = bone(steer, "fork_upper", 0.0000f, 0.0000f, 0.0000f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_upper, "outer_tube_l", 180, 19, 2.2400f, 3.2000f, 0.0000f, 1.3440f, 10.2400f, 1.3440f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_upper, "fork_cap_l", 52, 109, 2.2400f, -2.2400f, 0.0000f, 1.0240f, 0.6400f, 1.0240f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_upper, "outer_tube_r", 187, 19, -2.2400f, 3.2000f, 0.0000f, 1.3440f, 10.2400f, 1.3440f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_upper, "fork_cap_r", 58, 109, -2.2400f, -2.2400f, 0.0000f, 1.0240f, 0.6400f, 1.0240f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_upper, "top_clamp", 50, 97, 0.0000f, -2.2400f, 0.0000f, 6.0800f, 0.7040f, 2.2400f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_upper, "lower_clamp", 0, 82, 0.0000f, 2.4000f, -0.0000f, 6.0800f, 0.9600f, 2.4000f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_upper, "steerer", 171, 56, 0.0000f, 0.0000f, 0.0000f, 0.9600f, 4.8000f, 0.9600f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_upper, "front_plate", 176, 56, 0.0000f, -0.4800f, -2.4000f, 5.4400f, 4.8000f, 0.4480f, 8.0000f, -0.0000f, 0.0000f);
        cube(fork_upper, "bar_mount", 68, 97, 0.0000f, -3.0380f, -0.2975f, 1.9200f, 1.2800f, 1.2800f, 25.0000f, -0.0000f, 0.0000f);
        cube(fork_upper, "bar_pad", 76, 97, 0.0000f, -3.9951f, -0.7438f, 4.8000f, 1.2800f, 1.2800f, 25.0000f, -0.0000f, 0.0000f);
        cube(fork_upper, "bar_l", 183, 34, 4.4000f, -2.5519f, -0.3956f, 0.7040f, 0.7040f, 8.8029f, 93.2740f, 64.9797f, 92.4635f);
        cube(fork_upper, "bar_r", 204, 34, -4.4000f, -2.5519f, -0.3956f, 0.7040f, 0.7040f, 8.8029f, 93.2740f, -64.9797f, -92.4635f);
        cube(fork_upper, "crossbar", 48, 56, 0.0000f, -3.3157f, -0.8400f, 0.5120f, 0.5120f, 6.4000f, 90.0000f, 65.0000f, 90.0000f);
        cube(fork_upper, "grip_l", 107, 64, 10.5600f, -2.5906f, -0.5019f, 0.9600f, 0.9600f, 3.5200f, 90.0000f, 65.0000f, 90.0000f);
        cube(fork_upper, "grip_r", 117, 64, -10.5600f, -2.5906f, -0.5019f, 0.9600f, 0.9600f, 3.5200f, 90.0000f, -65.0000f, -90.0000f);
        cube(fork_upper, "clutch_perch", 90, 97, 8.1600f, -2.5906f, -0.5019f, 0.9600f, 1.0880f, 1.0880f, 25.0000f, -0.0000f, 0.0000f);
        cube(fork_upper, "clutch_lever", 115, 112, 9.9200f, -1.7984f, -1.8979f, 3.8400f, 0.3200f, 0.5120f, 25.6681f, -12.6653f, -6.0151f);
        cube(fork_upper, "brake_res", 64, 109, -7.8400f, -3.4607f, -0.9076f, 1.0880f, 0.9600f, 0.9600f, 25.0000f, -0.0000f, 0.0000f);
        cube(fork_upper, "brake_lever", 125, 112, -9.9200f, -1.7984f, -1.8979f, 3.8400f, 0.3200f, 0.5120f, 25.6681f, 12.6653f, 6.0151f);
        cube(fork_upper, "throttle", 96, 97, -8.6400f, -2.5906f, -0.5019f, 0.7040f, 1.2160f, 1.2160f, 25.0000f, -0.0000f, 0.0000f);
        PartDefinition fork_lower = bone(steer, "fork_lower", 0.0000f, 0.0000f, 0.0000f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_lower, "inner_tube_l", 123, 34, 2.2400f, 12.0000f, 0.0000f, 1.0240f, 9.9200f, 1.0240f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_lower, "seal_l", 101, 97, 2.2400f, 8.8000f, 0.0000f, 1.4720f, 0.6400f, 1.4720f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_lower, "axle_lug_l", 127, 64, 2.2400f, 18.0171f, -0.7786f, 1.2800f, 2.8800f, 1.6000f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_lower, "fork_guard_l", 134, 64, 2.2400f, 12.8000f, -0.9600f, 1.2800f, 4.4800f, 0.4480f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_lower, "inner_tube_r", 129, 34, -2.2400f, 12.0000f, 0.0000f, 1.0240f, 9.9200f, 1.0240f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_lower, "seal_r", 108, 97, -2.2400f, 8.8000f, 0.0000f, 1.4720f, 0.6400f, 1.4720f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_lower, "axle_lug_r", 139, 64, -2.2400f, 18.0171f, -0.7786f, 1.2800f, 2.8800f, 1.6000f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_lower, "fork_guard_r", 146, 64, -2.2400f, 12.8000f, -0.9600f, 1.2800f, 4.4800f, 0.4480f, -0.0000f, -0.0000f, 0.0000f);
        cube(fork_lower, "front_fender", 63, 56, 0.0000f, 8.9298f, -5.3692f, 3.0400f, 0.4480f, 6.4000f, 29.0000f, -0.0000f, 0.0000f);
        cube(fork_lower, "front_fender_tip", 18, 82, 0.0000f, 11.0070f, -8.4610f, 2.5600f, 0.4480f, 2.5600f, -1.0000f, -0.0000f, 0.0000f);
        cube(fork_lower, "front_fender_rear", 115, 97, 0.0000f, 7.7613f, -1.5005f, 2.5600f, 0.4480f, 2.2400f, 49.0000f, -0.0000f, 0.0000f);
        cube(fork_lower, "fender_stay_l", 135, 34, 1.9200f, 13.3768f, -2.9424f, 0.4480f, 9.6000f, 0.4480f, 25.0000f, -0.0000f, 0.0000f);
        cube(fork_lower, "fender_stay_r", 138, 34, -1.9200f, 13.3768f, -2.9424f, 0.4480f, 9.6000f, 0.4480f, 25.0000f, -0.0000f, 0.0000f);
        cube(fork_lower, "front_caliper", 30, 82, 2.4000f, 17.6971f, 0.8214f, 0.9600f, 2.2400f, 1.7600f, -0.0000f, -0.0000f, 0.0000f);
        PartDefinition front_wheel = bone(fork_lower, "front_wheel", 0.0000f, 18.0171f, -0.7786f, -0.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire0", 151, 64, 0.0000f, -7.2505f, -3.3809f, 2.4000f, 1.9200f, 2.1865f, 25.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall0", 37, 82, 0.0000f, -5.8584f, -2.7318f, 1.9680f, 1.6000f, 1.5223f, 25.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim0", 126, 97, 0.0000f, -5.1043f, -2.3802f, 1.0080f, 0.8320f, 1.3959f, 25.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire1", 162, 64, 0.0000f, -7.8210f, -1.6828f, 2.4000f, 1.9200f, 2.1865f, 37.8571f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall1", 45, 82, 0.0000f, -6.3194f, -1.3597f, 1.9680f, 1.6000f, 1.5223f, 37.8571f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim1", 132, 97, 0.0000f, -5.5060f, -1.1847f, 1.0080f, 0.8320f, 1.3959f, 37.8571f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire2", 173, 64, 0.0000f, -7.9994f, 0.0997f, 2.4000f, 1.9200f, 2.1865f, 50.7143f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall2", 53, 82, 0.0000f, -6.4635f, 0.0806f, 1.9680f, 1.6000f, 1.5223f, 50.7143f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim2", 138, 97, 0.0000f, -5.6316f, 0.0702f, 1.0080f, 0.8320f, 1.3959f, 50.7143f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire3", 184, 64, 0.0000f, -7.7766f, 1.8773f, 2.4000f, 1.9200f, 2.1865f, 63.5714f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall3", 61, 82, 0.0000f, -6.2835f, 1.5168f, 1.9680f, 1.6000f, 1.5223f, 63.5714f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim3", 144, 97, 0.0000f, -5.4747f, 1.3216f, 1.0080f, 0.8320f, 1.3959f, 63.5714f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire4", 195, 64, 0.0000f, -7.1639f, 3.5607f, 2.4000f, 1.9200f, 2.1865f, 76.4286f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall4", 69, 82, 0.0000f, -5.7884f, 2.8770f, 1.9680f, 1.6000f, 1.5223f, 76.4286f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim4", 150, 97, 0.0000f, -5.0434f, 2.5067f, 1.0080f, 0.8320f, 1.3959f, 76.4286f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire5", 206, 64, 0.0000f, -6.1920f, 5.0655f, 2.4000f, 1.9200f, 2.1865f, 89.2857f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall5", 77, 82, 0.0000f, -5.0031f, 4.0929f, 1.9680f, 1.6000f, 1.5223f, 89.2857f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim5", 156, 97, 0.0000f, -4.3592f, 3.5661f, 1.0080f, 0.8320f, 1.3959f, 89.2857f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire6", 217, 64, 0.0000f, -4.9096f, 6.3163f, 2.4000f, 1.9200f, 2.1865f, 102.1429f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall6", 85, 82, 0.0000f, -3.9669f, 5.1036f, 1.9680f, 1.6000f, 1.5223f, 102.1429f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim6", 162, 97, 0.0000f, -3.4563f, 4.4467f, 1.0080f, 0.8320f, 1.3959f, 102.1429f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire7", 228, 64, 0.0000f, -3.3809f, 7.2505f, 2.4000f, 1.9200f, 2.1865f, 115.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall7", 93, 82, 0.0000f, -2.7318f, 5.8584f, 1.9680f, 1.6000f, 1.5223f, 115.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim7", 168, 97, 0.0000f, -2.3802f, 5.1043f, 1.0080f, 0.8320f, 1.3959f, 115.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire8", 239, 64, 0.0000f, -1.6828f, 7.8210f, 2.4000f, 1.9200f, 2.1865f, 127.8571f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall8", 101, 82, 0.0000f, -1.3597f, 6.3194f, 1.9680f, 1.6000f, 1.5223f, 127.8571f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim8", 174, 97, 0.0000f, -1.1847f, 5.5060f, 1.0080f, 0.8320f, 1.3959f, 127.8571f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire9", 0, 70, 0.0000f, 0.0997f, 7.9994f, 2.4000f, 1.9200f, 2.1865f, 140.7143f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall9", 109, 82, 0.0000f, 0.0806f, 6.4635f, 1.9680f, 1.6000f, 1.5223f, 140.7143f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim9", 180, 97, 0.0000f, 0.0702f, 5.6316f, 1.0080f, 0.8320f, 1.3959f, 140.7143f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire10", 11, 70, 0.0000f, 1.8773f, 7.7766f, 2.4000f, 1.9200f, 2.1865f, 153.5714f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall10", 117, 82, 0.0000f, 1.5168f, 6.2835f, 1.9680f, 1.6000f, 1.5223f, 153.5714f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim10", 186, 97, 0.0000f, 1.3216f, 5.4747f, 1.0080f, 0.8320f, 1.3959f, 153.5714f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire11", 22, 70, 0.0000f, 3.5607f, 7.1639f, 2.4000f, 1.9200f, 2.1865f, 166.4286f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall11", 125, 82, 0.0000f, 2.8770f, 5.7884f, 1.9680f, 1.6000f, 1.5223f, 166.4286f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim11", 192, 97, 0.0000f, 2.5067f, 5.0434f, 1.0080f, 0.8320f, 1.3959f, 166.4286f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire12", 33, 70, 0.0000f, 5.0655f, 6.1920f, 2.4000f, 1.9200f, 2.1865f, 179.2857f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall12", 133, 82, 0.0000f, 4.0929f, 5.0031f, 1.9680f, 1.6000f, 1.5223f, 179.2857f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim12", 198, 97, 0.0000f, 3.5661f, 4.3592f, 1.0080f, 0.8320f, 1.3959f, 179.2857f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire13", 44, 70, 0.0000f, 6.3163f, 4.9096f, 2.4000f, 1.9200f, 2.1865f, -167.8571f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall13", 141, 82, 0.0000f, 5.1036f, 3.9669f, 1.9680f, 1.6000f, 1.5223f, -167.8571f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim13", 204, 97, 0.0000f, 4.4467f, 3.4563f, 1.0080f, 0.8320f, 1.3959f, -167.8571f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire14", 55, 70, 0.0000f, 7.2505f, 3.3809f, 2.4000f, 1.9200f, 2.1865f, -155.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall14", 149, 82, 0.0000f, 5.8584f, 2.7318f, 1.9680f, 1.6000f, 1.5223f, -155.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim14", 210, 97, 0.0000f, 5.1043f, 2.3802f, 1.0080f, 0.8320f, 1.3959f, -155.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire15", 66, 70, 0.0000f, 7.8210f, 1.6828f, 2.4000f, 1.9200f, 2.1865f, -142.1429f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall15", 157, 82, 0.0000f, 6.3194f, 1.3597f, 1.9680f, 1.6000f, 1.5223f, -142.1429f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim15", 216, 97, 0.0000f, 5.5060f, 1.1847f, 1.0080f, 0.8320f, 1.3959f, -142.1429f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire16", 77, 70, 0.0000f, 7.9994f, -0.0997f, 2.4000f, 1.9200f, 2.1865f, -129.2857f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall16", 165, 82, 0.0000f, 6.4635f, -0.0806f, 1.9680f, 1.6000f, 1.5223f, -129.2857f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim16", 222, 97, 0.0000f, 5.6316f, -0.0702f, 1.0080f, 0.8320f, 1.3959f, -129.2857f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire17", 88, 70, 0.0000f, 7.7766f, -1.8773f, 2.4000f, 1.9200f, 2.1865f, -116.4286f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall17", 173, 82, 0.0000f, 6.2835f, -1.5168f, 1.9680f, 1.6000f, 1.5223f, -116.4286f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim17", 228, 97, 0.0000f, 5.4747f, -1.3216f, 1.0080f, 0.8320f, 1.3959f, -116.4286f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire18", 99, 70, 0.0000f, 7.1639f, -3.5607f, 2.4000f, 1.9200f, 2.1865f, -103.5714f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall18", 181, 82, 0.0000f, 5.7884f, -2.8770f, 1.9680f, 1.6000f, 1.5223f, -103.5714f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim18", 234, 97, 0.0000f, 5.0434f, -2.5067f, 1.0080f, 0.8320f, 1.3959f, -103.5714f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire19", 110, 70, 0.0000f, 6.1920f, -5.0655f, 2.4000f, 1.9200f, 2.1865f, -90.7143f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall19", 189, 82, 0.0000f, 5.0031f, -4.0929f, 1.9680f, 1.6000f, 1.5223f, -90.7143f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim19", 240, 97, 0.0000f, 4.3592f, -3.5661f, 1.0080f, 0.8320f, 1.3959f, -90.7143f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire20", 121, 70, 0.0000f, 4.9096f, -6.3163f, 2.4000f, 1.9200f, 2.1865f, -77.8571f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall20", 197, 82, 0.0000f, 3.9669f, -5.1036f, 1.9680f, 1.6000f, 1.5223f, -77.8571f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim20", 246, 97, 0.0000f, 3.4563f, -4.4467f, 1.0080f, 0.8320f, 1.3959f, -77.8571f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire21", 132, 70, 0.0000f, 3.3809f, -7.2505f, 2.4000f, 1.9200f, 2.1865f, -65.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall21", 205, 82, 0.0000f, 2.7318f, -5.8584f, 1.9680f, 1.6000f, 1.5223f, -65.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim21", 0, 101, 0.0000f, 2.3802f, -5.1043f, 1.0080f, 0.8320f, 1.3959f, -65.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire22", 143, 70, 0.0000f, 1.6828f, -7.8210f, 2.4000f, 1.9200f, 2.1865f, -52.1429f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall22", 213, 82, 0.0000f, 1.3597f, -6.3194f, 1.9680f, 1.6000f, 1.5223f, -52.1429f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim22", 6, 101, 0.0000f, 1.1847f, -5.5060f, 1.0080f, 0.8320f, 1.3959f, -52.1429f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire23", 154, 70, 0.0000f, -0.0997f, -7.9994f, 2.4000f, 1.9200f, 2.1865f, -39.2857f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall23", 221, 82, 0.0000f, -0.0806f, -6.4635f, 1.9680f, 1.6000f, 1.5223f, -39.2857f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim23", 12, 101, 0.0000f, -0.0702f, -5.6316f, 1.0080f, 0.8320f, 1.3959f, -39.2857f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire24", 165, 70, 0.0000f, -1.8773f, -7.7766f, 2.4000f, 1.9200f, 2.1865f, -26.4286f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall24", 229, 82, 0.0000f, -1.5168f, -6.2835f, 1.9680f, 1.6000f, 1.5223f, -26.4286f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim24", 18, 101, 0.0000f, -1.3216f, -5.4747f, 1.0080f, 0.8320f, 1.3959f, -26.4286f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire25", 176, 70, 0.0000f, -3.5607f, -7.1639f, 2.4000f, 1.9200f, 2.1865f, -13.5714f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall25", 237, 82, 0.0000f, -2.8770f, -5.7884f, 1.9680f, 1.6000f, 1.5223f, -13.5714f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim25", 24, 101, 0.0000f, -2.5067f, -5.0434f, 1.0080f, 0.8320f, 1.3959f, -13.5714f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire26", 187, 70, 0.0000f, -5.0655f, -6.1920f, 2.4000f, 1.9200f, 2.1865f, -0.7143f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall26", 245, 82, 0.0000f, -4.0929f, -5.0031f, 1.9680f, 1.6000f, 1.5223f, -0.7143f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim26", 30, 101, 0.0000f, -3.5661f, -4.3592f, 1.0080f, 0.8320f, 1.3959f, -0.7143f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_tire27", 198, 70, 0.0000f, -6.3163f, -4.9096f, 2.4000f, 1.9200f, 2.1865f, 12.1429f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_wall27", 0, 87, 0.0000f, -5.1036f, -3.9669f, 1.9680f, 1.6000f, 1.5223f, 12.1429f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_rim27", 36, 101, 0.0000f, -4.4467f, -3.4563f, 1.0080f, 0.8320f, 1.3959f, 12.1429f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob0_0", 70, 109, 0.0000f, -8.6129f, -2.4697f, 0.9600f, 0.6400f, 0.8320f, 34.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob1_0", 75, 109, -0.7200f, -8.9545f, 0.3127f, 0.7200f, 0.6400f, 0.8320f, 52.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob1_1", 80, 109, 0.7200f, -8.9545f, 0.3127f, 0.7200f, 0.6400f, 0.8320f, 52.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob2_0", 85, 109, 0.0000f, -8.4196f, 3.0645f, 0.9600f, 0.6400f, 0.8320f, 70.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob3_0", 90, 109, -0.7200f, -7.0606f, 5.5163f, 0.7200f, 0.6400f, 0.8320f, 88.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob3_1", 95, 109, 0.7200f, -7.0606f, 5.5163f, 0.7200f, 0.6400f, 0.8320f, 88.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob4_0", 100, 109, 0.0000f, -5.0104f, 7.4282f, 0.9600f, 0.6400f, 0.8320f, 106.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob5_0", 105, 109, -0.7200f, -2.4697f, 8.6129f, 0.7200f, 0.6400f, 0.8320f, 124.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob5_1", 110, 109, 0.7200f, -2.4697f, 8.6129f, 0.7200f, 0.6400f, 0.8320f, 124.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob6_0", 115, 109, 0.0000f, 0.3127f, 8.9545f, 0.9600f, 0.6400f, 0.8320f, 142.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob7_0", 120, 109, -0.7200f, 3.0645f, 8.4196f, 0.7200f, 0.6400f, 0.8320f, 160.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob7_1", 125, 109, 0.7200f, 3.0645f, 8.4196f, 0.7200f, 0.6400f, 0.8320f, 160.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob8_0", 130, 109, 0.0000f, 5.5163f, 7.0606f, 0.9600f, 0.6400f, 0.8320f, 178.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob9_0", 135, 109, -0.7200f, 7.4282f, 5.0104f, 0.7200f, 0.6400f, 0.8320f, -164.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob9_1", 140, 109, 0.7200f, 7.4282f, 5.0104f, 0.7200f, 0.6400f, 0.8320f, -164.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob10_0", 145, 109, 0.0000f, 8.6129f, 2.4697f, 0.9600f, 0.6400f, 0.8320f, -146.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob11_0", 150, 109, -0.7200f, 8.9545f, -0.3127f, 0.7200f, 0.6400f, 0.8320f, -128.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob11_1", 155, 109, 0.7200f, 8.9545f, -0.3127f, 0.7200f, 0.6400f, 0.8320f, -128.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob12_0", 160, 109, 0.0000f, 8.4196f, -3.0645f, 0.9600f, 0.6400f, 0.8320f, -110.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob13_0", 165, 109, -0.7200f, 7.0606f, -5.5163f, 0.7200f, 0.6400f, 0.8320f, -92.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob13_1", 170, 109, 0.7200f, 7.0606f, -5.5163f, 0.7200f, 0.6400f, 0.8320f, -92.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob14_0", 175, 109, 0.0000f, 5.0104f, -7.4282f, 0.9600f, 0.6400f, 0.8320f, -74.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob15_0", 180, 109, -0.7200f, 2.4697f, -8.6129f, 0.7200f, 0.6400f, 0.8320f, -56.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob15_1", 185, 109, 0.7200f, 2.4697f, -8.6129f, 0.7200f, 0.6400f, 0.8320f, -56.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob16_0", 190, 109, 0.0000f, -0.3127f, -8.9545f, 0.9600f, 0.6400f, 0.8320f, -38.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob17_0", 195, 109, -0.7200f, -3.0645f, -8.4196f, 0.7200f, 0.6400f, 0.8320f, -20.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob17_1", 200, 109, 0.7200f, -3.0645f, -8.4196f, 0.7200f, 0.6400f, 0.8320f, -20.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob18_0", 205, 109, 0.0000f, -5.5163f, -7.0606f, 0.9600f, 0.6400f, 0.8320f, -2.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob19_0", 210, 109, -0.7200f, -7.4282f, -5.0104f, 0.7200f, 0.6400f, 0.8320f, 16.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_knob19_1", 215, 109, 0.7200f, -7.4282f, -5.0104f, 0.7200f, 0.6400f, 0.8320f, 16.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_spoke0", 209, 70, -0.4000f, -2.3725f, -2.1052f, 0.2240f, 0.2240f, 4.2800f, -142.1736f, 15.1175f, 172.7631f);
        cube(front_wheel, "f_spoke1", 220, 70, 0.4000f, -3.0765f, 0.7718f, 0.2240f, 0.2240f, 4.2800f, 67.1610f, -8.8941f, -4.1848f);
        cube(front_wheel, "f_spoke2", 231, 70, -0.4000f, -3.1662f, 0.1891f, 0.2240f, 0.2240f, 4.2800f, 95.4932f, 18.7396f, 9.1022f);
        cube(front_wheel, "f_spoke3", 242, 70, 0.4000f, -1.6297f, 2.7212f, 0.2240f, 0.2240f, 4.2800f, 22.4581f, -6.6223f, -3.1034f);
        cube(front_wheel, "f_spoke4", 0, 76, -0.4000f, -2.1052f, 2.3725f, 0.2240f, 0.2240f, 4.2800f, 50.2436f, 7.3037f, 3.4264f);
        cube(front_wheel, "f_spoke5", 11, 76, 0.4000f, 0.7718f, 3.0765f, 0.2240f, 0.2240f, 4.2800f, -21.8412f, -9.7676f, -4.6043f);
        cube(front_wheel, "f_spoke6", 22, 76, -0.4000f, 0.1891f, 3.1662f, 0.2240f, 0.2240f, 4.2800f, 5.6128f, 7.0232f, 3.2933f);
        cube(front_wheel, "f_spoke7", 33, 76, 0.4000f, 2.7212f, 1.6297f, 0.2240f, 0.2240f, 4.2800f, 44.6852f, -58.1031f, -131.4749f);
        cube(front_wheel, "f_spoke8", 44, 76, -0.4000f, 2.3725f, 2.1052f, 0.2240f, 0.2240f, 4.2800f, -37.8264f, 15.1175f, 7.2369f);
        cube(front_wheel, "f_spoke9", 55, 76, 0.4000f, 3.0765f, -0.7718f, 0.2240f, 0.2240f, 4.2800f, 112.8390f, -8.8941f, -175.8152f);
        cube(front_wheel, "f_spoke10", 66, 76, -0.4000f, 3.1662f, -0.1891f, 0.2240f, 0.2240f, 4.2800f, 84.5068f, 18.7396f, 170.8978f);
        cube(front_wheel, "f_spoke11", 77, 76, 0.4000f, 1.6297f, -2.7212f, 0.2240f, 0.2240f, 4.2800f, 157.5419f, -6.6223f, -176.8966f);
        cube(front_wheel, "f_spoke12", 88, 76, -0.4000f, 2.1052f, -2.3725f, 0.2240f, 0.2240f, 4.2800f, 129.7564f, 7.3037f, 176.5736f);
        cube(front_wheel, "f_spoke13", 99, 76, 0.4000f, -0.7718f, -3.0765f, 0.2240f, 0.2240f, 4.2800f, -158.1588f, -9.7676f, -175.3957f);
        cube(front_wheel, "f_spoke14", 110, 76, -0.4000f, -0.1891f, -3.1662f, 0.2240f, 0.2240f, 4.2800f, 174.3872f, 7.0232f, 176.7067f);
        cube(front_wheel, "f_spoke15", 121, 76, 0.4000f, -2.7212f, -1.6297f, 0.2240f, 0.2240f, 4.2800f, 135.3148f, -58.1031f, -48.5251f);
        cube(front_wheel, "f_hub", 8, 87, 0.0000f, 0.0000f, 0.0000f, 2.9120f, 1.7920f, 1.7920f, 25.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_hub_l", 132, 76, 0.8960f, 0.0000f, 0.0000f, 0.5600f, 2.4640f, 2.4640f, 25.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_hub_r", 140, 76, -0.8960f, 0.0000f, 0.0000f, 0.5600f, 2.4640f, 2.4640f, 25.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_disc0", 161, 46, 1.5680f, 0.0000f, 0.0000f, 0.1920f, 5.9584f, 1.2820f, 25.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_disc1", 165, 46, 1.5680f, 0.0000f, 0.0000f, 0.1920f, 5.9584f, 1.2820f, 47.5000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_disc2", 169, 46, 1.5680f, 0.0000f, 0.0000f, 0.1920f, 5.9584f, 1.2820f, 70.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_disc3", 173, 46, 1.5680f, 0.0000f, 0.0000f, 0.1920f, 5.9584f, 1.2820f, 92.5000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_disc4", 177, 46, 1.5680f, 0.0000f, 0.0000f, 0.1920f, 5.9584f, 1.2820f, 115.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_disc5", 181, 46, 1.5680f, 0.0000f, 0.0000f, 0.1920f, 5.9584f, 1.2820f, 137.5000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_disc6", 185, 46, 1.5680f, 0.0000f, 0.0000f, 0.1920f, 5.9584f, 1.2820f, 160.0000f, -0.0000f, 0.0000f);
        cube(front_wheel, "f_disc7", 189, 46, 1.5680f, 0.0000f, 0.0000f, 0.1920f, 5.9584f, 1.2820f, -177.5000f, -0.0000f, 0.0000f);
        PartDefinition swingarm = bone(frame, "swingarm", 0.0000f, -10.5600f, 3.2000f, 0.0000f, -0.0000f, 0.0000f);
        cube(swingarm, "arm_l", 173, 0, 2.4000f, 0.6720f, 7.3600f, 1.2800f, 1.6000f, 13.1887f, -5.8489f, -0.0000f, 0.0000f);
        cube(swingarm, "chain_adjuster_l", 42, 101, 2.4000f, 1.6000f, 15.2000f, 0.7680f, 1.1200f, 1.6000f, 0.0000f, -0.0000f, 0.0000f);
        cube(swingarm, "arm_r", 203, 0, -2.4000f, 0.6720f, 7.3600f, 1.2800f, 1.6000f, 13.1887f, -5.8489f, -0.0000f, 0.0000f);
        cube(swingarm, "chain_adjuster_r", 48, 101, -2.4000f, 1.6000f, 15.2000f, 0.7680f, 1.1200f, 1.6000f, 0.0000f, -0.0000f, 0.0000f);
        cube(swingarm, "arm_brace", 54, 101, 0.0000f, 0.6400f, 7.6800f, 4.8000f, 0.9600f, 1.2800f, 0.0000f, -0.0000f, 0.0000f);
        cube(swingarm, "linkage", 148, 76, 0.0000f, 0.6400f, 2.8800f, 1.6000f, 1.2800f, 2.8800f, 15.0000f, -0.0000f, 0.0000f);
        cube(swingarm, "chain_slider", 189, 56, 3.3600f, -0.3200f, 6.4000f, 0.5120f, 0.6400f, 5.1200f, 0.0000f, -0.0000f, 0.0000f);
        cube(swingarm, "chain_top", 0, 0, 3.4080f, -0.5120f, 6.2400f, 0.3200f, 0.4480f, 16.9912f, 3.4551f, -0.3243f, 0.0000f);
        cube(swingarm, "chain_bot", 36, 0, 3.4080f, 3.0720f, 6.2400f, 0.3200f, 0.4480f, 17.1161f, -7.7361f, -0.3243f, 0.0000f);
        cube(swingarm, "rear_caliper", 19, 87, -2.7200f, -0.6400f, 12.8000f, 0.8960f, 1.6000f, 1.6000f, 0.0000f, -0.0000f, 0.0000f);
        PartDefinition rear_wheel = bone(swingarm, "rear_wheel", 0.0000f, 1.6000f, 14.7200f, 0.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire0", 25, 87, 0.0000f, -7.3600f, 0.0000f, 2.8800f, 1.9200f, 2.0358f, 0.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall0", 68, 101, 0.0000f, -5.6640f, 0.0000f, 2.3616f, 1.6000f, 1.3320f, 0.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim0", 77, 101, 0.0000f, -4.8320f, 0.0000f, 1.2096f, 0.8320f, 1.2021f, 0.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire1", 36, 87, 0.0000f, -7.1755f, 1.6378f, 2.8800f, 1.9200f, 2.0358f, 12.8571f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall1", 83, 101, 0.0000f, -5.5220f, 1.2604f, 2.3616f, 1.6000f, 1.3320f, 12.8571f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim1", 92, 101, 0.0000f, -4.7109f, 1.0752f, 1.2096f, 0.8320f, 1.2021f, 12.8571f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire2", 47, 87, 0.0000f, -6.6311f, 3.1934f, 2.8800f, 1.9200f, 2.0358f, 25.7143f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall2", 98, 101, 0.0000f, -5.1031f, 2.4575f, 2.3616f, 1.6000f, 1.3320f, 25.7143f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim2", 107, 101, 0.0000f, -4.3535f, 2.0965f, 1.2096f, 0.8320f, 1.2021f, 25.7143f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire3", 58, 87, 0.0000f, -5.7543f, 4.5889f, 2.8800f, 1.9200f, 2.0358f, 38.5714f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall3", 113, 101, 0.0000f, -4.4283f, 3.5314f, 2.3616f, 1.6000f, 1.3320f, 38.5714f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim3", 122, 101, 0.0000f, -3.7778f, 3.0127f, 1.2096f, 0.8320f, 1.2021f, 38.5714f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire4", 69, 87, 0.0000f, -4.5889f, 5.7543f, 2.8800f, 1.9200f, 2.0358f, 51.4286f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall4", 128, 101, 0.0000f, -3.5314f, 4.4283f, 2.3616f, 1.6000f, 1.3320f, 51.4286f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim4", 137, 101, 0.0000f, -3.0127f, 3.7778f, 1.2096f, 0.8320f, 1.2021f, 51.4286f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire5", 80, 87, 0.0000f, -3.1934f, 6.6311f, 2.8800f, 1.9200f, 2.0358f, 64.2857f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall5", 143, 101, 0.0000f, -2.4575f, 5.1031f, 2.3616f, 1.6000f, 1.3320f, 64.2857f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim5", 152, 101, 0.0000f, -2.0965f, 4.3535f, 1.2096f, 0.8320f, 1.2021f, 64.2857f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire6", 91, 87, 0.0000f, -1.6378f, 7.1755f, 2.8800f, 1.9200f, 2.0358f, 77.1429f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall6", 158, 101, 0.0000f, -1.2604f, 5.5220f, 2.3616f, 1.6000f, 1.3320f, 77.1429f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim6", 167, 101, 0.0000f, -1.0752f, 4.7109f, 1.2096f, 0.8320f, 1.2021f, 77.1429f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire7", 102, 87, 0.0000f, 0.0000f, 7.3600f, 2.8800f, 1.9200f, 2.0358f, 90.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall7", 173, 101, 0.0000f, 0.0000f, 5.6640f, 2.3616f, 1.6000f, 1.3320f, 90.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim7", 182, 101, 0.0000f, 0.0000f, 4.8320f, 1.2096f, 0.8320f, 1.2021f, 90.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire8", 113, 87, 0.0000f, 1.6378f, 7.1755f, 2.8800f, 1.9200f, 2.0358f, 102.8571f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall8", 188, 101, 0.0000f, 1.2604f, 5.5220f, 2.3616f, 1.6000f, 1.3320f, 102.8571f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim8", 197, 101, 0.0000f, 1.0752f, 4.7109f, 1.2096f, 0.8320f, 1.2021f, 102.8571f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire9", 124, 87, 0.0000f, 3.1934f, 6.6311f, 2.8800f, 1.9200f, 2.0358f, 115.7143f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall9", 203, 101, 0.0000f, 2.4575f, 5.1031f, 2.3616f, 1.6000f, 1.3320f, 115.7143f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim9", 212, 101, 0.0000f, 2.0965f, 4.3535f, 1.2096f, 0.8320f, 1.2021f, 115.7143f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire10", 135, 87, 0.0000f, 4.5889f, 5.7543f, 2.8800f, 1.9200f, 2.0358f, 128.5714f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall10", 218, 101, 0.0000f, 3.5314f, 4.4283f, 2.3616f, 1.6000f, 1.3320f, 128.5714f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim10", 227, 101, 0.0000f, 3.0127f, 3.7778f, 1.2096f, 0.8320f, 1.2021f, 128.5714f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire11", 146, 87, 0.0000f, 5.7543f, 4.5889f, 2.8800f, 1.9200f, 2.0358f, 141.4286f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall11", 233, 101, 0.0000f, 4.4283f, 3.5314f, 2.3616f, 1.6000f, 1.3320f, 141.4286f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim11", 242, 101, 0.0000f, 3.7778f, 3.0127f, 1.2096f, 0.8320f, 1.2021f, 141.4286f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire12", 157, 87, 0.0000f, 6.6311f, 3.1934f, 2.8800f, 1.9200f, 2.0358f, 154.2857f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall12", 0, 105, 0.0000f, 5.1031f, 2.4575f, 2.3616f, 1.6000f, 1.3320f, 154.2857f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim12", 9, 105, 0.0000f, 4.3535f, 2.0965f, 1.2096f, 0.8320f, 1.2021f, 154.2857f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire13", 168, 87, 0.0000f, 7.1755f, 1.6378f, 2.8800f, 1.9200f, 2.0358f, 167.1429f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall13", 15, 105, 0.0000f, 5.5220f, 1.2604f, 2.3616f, 1.6000f, 1.3320f, 167.1429f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim13", 24, 105, 0.0000f, 4.7109f, 1.0752f, 1.2096f, 0.8320f, 1.2021f, 167.1429f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire14", 179, 87, 0.0000f, 7.3600f, 0.0000f, 2.8800f, 1.9200f, 2.0358f, 180.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall14", 30, 105, 0.0000f, 5.6640f, 0.0000f, 2.3616f, 1.6000f, 1.3320f, 180.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim14", 39, 105, 0.0000f, 4.8320f, 0.0000f, 1.2096f, 0.8320f, 1.2021f, 180.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire15", 190, 87, 0.0000f, 7.1755f, -1.6378f, 2.8800f, 1.9200f, 2.0358f, -167.1429f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall15", 45, 105, 0.0000f, 5.5220f, -1.2604f, 2.3616f, 1.6000f, 1.3320f, -167.1429f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim15", 54, 105, 0.0000f, 4.7109f, -1.0752f, 1.2096f, 0.8320f, 1.2021f, -167.1429f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire16", 201, 87, 0.0000f, 6.6311f, -3.1934f, 2.8800f, 1.9200f, 2.0358f, -154.2857f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall16", 60, 105, 0.0000f, 5.1031f, -2.4575f, 2.3616f, 1.6000f, 1.3320f, -154.2857f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim16", 69, 105, 0.0000f, 4.3535f, -2.0965f, 1.2096f, 0.8320f, 1.2021f, -154.2857f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire17", 212, 87, 0.0000f, 5.7543f, -4.5889f, 2.8800f, 1.9200f, 2.0358f, -141.4286f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall17", 75, 105, 0.0000f, 4.4283f, -3.5314f, 2.3616f, 1.6000f, 1.3320f, -141.4286f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim17", 84, 105, 0.0000f, 3.7778f, -3.0127f, 1.2096f, 0.8320f, 1.2021f, -141.4286f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire18", 223, 87, 0.0000f, 4.5889f, -5.7543f, 2.8800f, 1.9200f, 2.0358f, -128.5714f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall18", 90, 105, 0.0000f, 3.5314f, -4.4283f, 2.3616f, 1.6000f, 1.3320f, -128.5714f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim18", 99, 105, 0.0000f, 3.0127f, -3.7778f, 1.2096f, 0.8320f, 1.2021f, -128.5714f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire19", 234, 87, 0.0000f, 3.1934f, -6.6311f, 2.8800f, 1.9200f, 2.0358f, -115.7143f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall19", 105, 105, 0.0000f, 2.4575f, -5.1031f, 2.3616f, 1.6000f, 1.3320f, -115.7143f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim19", 114, 105, 0.0000f, 2.0965f, -4.3535f, 1.2096f, 0.8320f, 1.2021f, -115.7143f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire20", 245, 87, 0.0000f, 1.6378f, -7.1755f, 2.8800f, 1.9200f, 2.0358f, -102.8571f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall20", 120, 105, 0.0000f, 1.2604f, -5.5220f, 2.3616f, 1.6000f, 1.3320f, -102.8571f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim20", 129, 105, 0.0000f, 1.0752f, -4.7109f, 1.2096f, 0.8320f, 1.2021f, -102.8571f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire21", 0, 92, 0.0000f, 0.0000f, -7.3600f, 2.8800f, 1.9200f, 2.0358f, -90.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall21", 135, 105, 0.0000f, 0.0000f, -5.6640f, 2.3616f, 1.6000f, 1.3320f, -90.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim21", 144, 105, 0.0000f, 0.0000f, -4.8320f, 1.2096f, 0.8320f, 1.2021f, -90.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire22", 11, 92, 0.0000f, -1.6378f, -7.1755f, 2.8800f, 1.9200f, 2.0358f, -77.1429f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall22", 150, 105, 0.0000f, -1.2604f, -5.5220f, 2.3616f, 1.6000f, 1.3320f, -77.1429f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim22", 159, 105, 0.0000f, -1.0752f, -4.7109f, 1.2096f, 0.8320f, 1.2021f, -77.1429f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire23", 22, 92, 0.0000f, -3.1934f, -6.6311f, 2.8800f, 1.9200f, 2.0358f, -64.2857f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall23", 165, 105, 0.0000f, -2.4575f, -5.1031f, 2.3616f, 1.6000f, 1.3320f, -64.2857f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim23", 174, 105, 0.0000f, -2.0965f, -4.3535f, 1.2096f, 0.8320f, 1.2021f, -64.2857f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire24", 33, 92, 0.0000f, -4.5889f, -5.7543f, 2.8800f, 1.9200f, 2.0358f, -51.4286f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall24", 180, 105, 0.0000f, -3.5314f, -4.4283f, 2.3616f, 1.6000f, 1.3320f, -51.4286f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim24", 189, 105, 0.0000f, -3.0127f, -3.7778f, 1.2096f, 0.8320f, 1.2021f, -51.4286f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire25", 44, 92, 0.0000f, -5.7543f, -4.5889f, 2.8800f, 1.9200f, 2.0358f, -38.5714f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall25", 195, 105, 0.0000f, -4.4283f, -3.5314f, 2.3616f, 1.6000f, 1.3320f, -38.5714f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim25", 204, 105, 0.0000f, -3.7778f, -3.0127f, 1.2096f, 0.8320f, 1.2021f, -38.5714f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire26", 55, 92, 0.0000f, -6.6311f, -3.1934f, 2.8800f, 1.9200f, 2.0358f, -25.7143f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall26", 210, 105, 0.0000f, -5.1031f, -2.4575f, 2.3616f, 1.6000f, 1.3320f, -25.7143f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim26", 219, 105, 0.0000f, -4.3535f, -2.0965f, 1.2096f, 0.8320f, 1.2021f, -25.7143f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_tire27", 66, 92, 0.0000f, -7.1755f, -1.6378f, 2.8800f, 1.9200f, 2.0358f, -12.8571f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_wall27", 225, 105, 0.0000f, -5.5220f, -1.2604f, 2.3616f, 1.6000f, 1.3320f, -12.8571f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_rim27", 234, 105, 0.0000f, -4.7109f, -1.0752f, 1.2096f, 0.8320f, 1.2021f, -12.8571f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob0_0", 220, 109, 0.0000f, -8.2176f, 1.3015f, 1.1520f, 0.6400f, 0.8320f, 9.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob1_0", 225, 109, -0.8640f, -7.4132f, 3.7772f, 0.8640f, 0.6400f, 0.8320f, 27.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob1_1", 230, 109, 0.8640f, -7.4132f, 3.7772f, 0.8640f, 0.6400f, 0.8320f, 27.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob2_0", 235, 109, 0.0000f, -5.8831f, 5.8831f, 1.1520f, 0.6400f, 0.8320f, 45.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob3_0", 240, 109, -0.8640f, -3.7772f, 7.4132f, 0.8640f, 0.6400f, 0.8320f, 63.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob3_1", 245, 109, 0.8640f, -3.7772f, 7.4132f, 0.8640f, 0.6400f, 0.8320f, 63.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob4_0", 250, 109, 0.0000f, -1.3015f, 8.2176f, 1.1520f, 0.6400f, 0.8320f, 81.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob5_0", 0, 112, -0.8640f, 1.3015f, 8.2176f, 0.8640f, 0.6400f, 0.8320f, 99.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob5_1", 5, 112, 0.8640f, 1.3015f, 8.2176f, 0.8640f, 0.6400f, 0.8320f, 99.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob6_0", 10, 112, 0.0000f, 3.7772f, 7.4132f, 1.1520f, 0.6400f, 0.8320f, 117.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob7_0", 15, 112, -0.8640f, 5.8831f, 5.8831f, 0.8640f, 0.6400f, 0.8320f, 135.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob7_1", 20, 112, 0.8640f, 5.8831f, 5.8831f, 0.8640f, 0.6400f, 0.8320f, 135.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob8_0", 25, 112, 0.0000f, 7.4132f, 3.7772f, 1.1520f, 0.6400f, 0.8320f, 153.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob9_0", 30, 112, -0.8640f, 8.2176f, 1.3015f, 0.8640f, 0.6400f, 0.8320f, 171.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob9_1", 35, 112, 0.8640f, 8.2176f, 1.3015f, 0.8640f, 0.6400f, 0.8320f, 171.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob10_0", 40, 112, 0.0000f, 8.2176f, -1.3015f, 1.1520f, 0.6400f, 0.8320f, -171.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob11_0", 45, 112, -0.8640f, 7.4132f, -3.7772f, 0.8640f, 0.6400f, 0.8320f, -153.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob11_1", 50, 112, 0.8640f, 7.4132f, -3.7772f, 0.8640f, 0.6400f, 0.8320f, -153.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob12_0", 55, 112, 0.0000f, 5.8831f, -5.8831f, 1.1520f, 0.6400f, 0.8320f, -135.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob13_0", 60, 112, -0.8640f, 3.7772f, -7.4132f, 0.8640f, 0.6400f, 0.8320f, -117.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob13_1", 65, 112, 0.8640f, 3.7772f, -7.4132f, 0.8640f, 0.6400f, 0.8320f, -117.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob14_0", 70, 112, 0.0000f, 1.3015f, -8.2176f, 1.1520f, 0.6400f, 0.8320f, -99.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob15_0", 75, 112, -0.8640f, -1.3015f, -8.2176f, 0.8640f, 0.6400f, 0.8320f, -81.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob15_1", 80, 112, 0.8640f, -1.3015f, -8.2176f, 0.8640f, 0.6400f, 0.8320f, -81.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob16_0", 85, 112, 0.0000f, -3.7772f, -7.4132f, 1.1520f, 0.6400f, 0.8320f, -63.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob17_0", 90, 112, -0.8640f, -5.8831f, -5.8831f, 0.8640f, 0.6400f, 0.8320f, -45.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob17_1", 95, 112, 0.8640f, -5.8831f, -5.8831f, 0.8640f, 0.6400f, 0.8320f, -45.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob18_0", 100, 112, 0.0000f, -7.4132f, -3.7772f, 1.1520f, 0.6400f, 0.8320f, -27.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob19_0", 105, 112, -0.8640f, -8.2176f, -1.3015f, 0.8640f, 0.6400f, 0.8320f, -9.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_knob19_1", 110, 112, 0.8640f, -8.2176f, -1.3015f, 0.8640f, 0.6400f, 0.8320f, -9.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_spoke0", 77, 92, -0.4000f, -2.6642f, -0.7681f, 0.2240f, 0.2240f, 3.4920f, -117.8194f, 19.5003f, 180.0000f);
        cube(rear_wheel, "r_spoke1", 86, 92, 0.4000f, -2.1675f, 1.7292f, 0.2240f, 0.2240f, 3.4920f, 40.4475f, -11.8126f, 0.0000f);
        cube(rear_wheel, "r_spoke2", 95, 92, -0.4000f, -2.4270f, 1.3407f, 0.2240f, 0.2240f, 3.4920f, 69.4636f, 26.3647f, 0.0000f);
        cube(rear_wheel, "r_spoke3", 104, 92, 0.4000f, -0.3099f, 2.7553f, 0.2240f, 0.2240f, 3.4920f, -3.8978f, -8.9833f, 0.0000f);
        cube(rear_wheel, "r_spoke4", 113, 92, -0.4000f, -0.7681f, 2.6642f, 0.2240f, 0.2240f, 3.4920f, 26.0986f, 9.9898f, 0.0000f);
        cube(rear_wheel, "r_spoke5", 122, 92, 0.4000f, 1.7292f, 2.1675f, 0.2240f, 0.2240f, 3.4920f, -48.1492f, -13.5028f, 0.0000f);
        cube(rear_wheel, "r_spoke6", 131, 92, -0.4000f, 1.3407f, 2.4270f, 0.2240f, 0.2240f, 3.4920f, -18.3194f, 9.4451f, 0.0000f);
        cube(rear_wheel, "r_spoke7", 140, 92, 0.4000f, 2.7553f, 0.3099f, 0.2240f, 0.2240f, 3.4920f, 99.7861f, -66.4262f, 180.0000f);
        cube(rear_wheel, "r_spoke8", 149, 92, -0.4000f, 2.6642f, 0.7681f, 0.2240f, 0.2240f, 3.4920f, -62.1806f, 19.5003f, 0.0000f);
        cube(rear_wheel, "r_spoke9", 158, 92, 0.4000f, 2.1675f, -1.7292f, 0.2240f, 0.2240f, 3.4920f, 139.5525f, -11.8126f, 180.0000f);
        cube(rear_wheel, "r_spoke10", 167, 92, -0.4000f, 2.4270f, -1.3407f, 0.2240f, 0.2240f, 3.4920f, 110.5364f, 26.3647f, 180.0000f);
        cube(rear_wheel, "r_spoke11", 176, 92, 0.4000f, 0.3099f, -2.7553f, 0.2240f, 0.2240f, 3.4920f, -176.1022f, -8.9833f, 180.0000f);
        cube(rear_wheel, "r_spoke12", 185, 92, -0.4000f, 0.7681f, -2.6642f, 0.2240f, 0.2240f, 3.4920f, 153.9014f, 9.9898f, 180.0000f);
        cube(rear_wheel, "r_spoke13", 194, 92, 0.4000f, -1.7292f, -2.1675f, 0.2240f, 0.2240f, 3.4920f, -131.8508f, -13.5028f, 180.0000f);
        cube(rear_wheel, "r_spoke14", 203, 92, -0.4000f, -1.3407f, -2.4270f, 0.2240f, 0.2240f, 3.4920f, -161.6806f, 9.4451f, 180.0000f);
        cube(rear_wheel, "r_spoke15", 212, 92, 0.4000f, -2.7553f, -0.3099f, 0.2240f, 0.2240f, 3.4920f, 80.2139f, -66.4262f, 0.0000f);
        cube(rear_wheel, "r_hub", 221, 92, 0.0000f, 0.0000f, 0.0000f, 3.3600f, 1.7920f, 1.7920f, 0.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_hub_l", 158, 76, 0.8960f, 0.0000f, 0.0000f, 0.5600f, 2.4640f, 2.4640f, 0.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_hub_r", 166, 76, -0.8960f, 0.0000f, 0.0000f, 0.5600f, 2.4640f, 2.4640f, 0.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_disc0", 83, 56, -1.5680f, 0.0000f, 0.0000f, 0.1920f, 5.3312f, 1.1470f, 0.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_disc1", 87, 56, -1.5680f, 0.0000f, 0.0000f, 0.1920f, 5.3312f, 1.1470f, 22.5000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_disc2", 91, 56, -1.5680f, 0.0000f, 0.0000f, 0.1920f, 5.3312f, 1.1470f, 45.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_disc3", 95, 56, -1.5680f, 0.0000f, 0.0000f, 0.1920f, 5.3312f, 1.1470f, 67.5000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_disc4", 99, 56, -1.5680f, 0.0000f, 0.0000f, 0.1920f, 5.3312f, 1.1470f, 90.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_disc5", 103, 56, -1.5680f, 0.0000f, 0.0000f, 0.1920f, 5.3312f, 1.1470f, 112.5000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_disc6", 107, 56, -1.5680f, 0.0000f, 0.0000f, 0.1920f, 5.3312f, 1.1470f, 135.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_disc7", 111, 56, -1.5680f, 0.0000f, 0.0000f, 0.1920f, 5.3312f, 1.1470f, 157.5000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_sprocket0", 193, 46, 3.3600f, 0.0000f, 0.0000f, 0.2560f, 5.4400f, 1.5743f, 0.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_sprocket1", 198, 46, 3.3600f, 0.0000f, 0.0000f, 0.2560f, 5.4400f, 1.5743f, 30.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_sprocket2", 203, 46, 3.3600f, 0.0000f, 0.0000f, 0.2560f, 5.4400f, 1.5743f, 60.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_sprocket3", 208, 46, 3.3600f, 0.0000f, 0.0000f, 0.2560f, 5.4400f, 1.5743f, 90.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_sprocket4", 213, 46, 3.3600f, 0.0000f, 0.0000f, 0.2560f, 5.4400f, 1.5743f, 120.0000f, -0.0000f, 0.0000f);
        cube(rear_wheel, "r_sprocket5", 218, 46, 3.3600f, 0.0000f, 0.0000f, 0.2560f, 5.4400f, 1.5743f, 150.0000f, -0.0000f, 0.0000f);
        // </GENERATED>
        return LayerDefinition.create(mesh, 256, 256);
    }
}
