package com.descentmtb.client.model;

import com.descentmtb.DescentMtb;
import com.descentmtb.client.ski.SkiStance;
import com.descentmtb.entity.MountainBikeEntity;
import com.descentmtb.ski.SkiBrand;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import com.mojang.math.Axis;
import java.util.Map;
import java.util.WeakHashMap;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.Model;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.resources.ResourceLocation;

/**
 * The skis, one real pair per {@link SkiBrand}: real length, the sidecut from the brand's radius (wider shovel and
 * tail than the waist), a thin profile (steel-edged base strip under the core, 17 mm under the foot, thinner toward
 * the ends), race skis with a low tip, a flat square tail and a 15 mm binding plate, freestyle twins with a high tip
 * and a turned-up tail and a turntable heel; toe and heel piece with ski brakes, a buckled hard-shell boot, and the
 * pole the rider holds. Each brand has its own texture ({@code textures/entity/ski/<id>.png}, same layout size): the
 * top-sheet graphic with the maker's lettering, the base, the boot and pole colours.
 *
 * <pre>
 * root
 *  `- &lt;brand id&gt;        one per SkiBrand
 *      |- ski          ONE ski: base strips, cores, shovel / tail segments, plate, toe and heel piece
 *      |   `- brake    brake arms and pads; xRot swings them down when nobody stands in the bindings
 *      |- boot         sole, lugs, lower shell, toe box, instep, lower buckles
 *      |   `- cuff     cuff, tongue, spoiler, power strap, cuff buckles; pivots about the sole centre (shin lean)
 *      `- pole         one pole in its hand frame (see {@link #renderPole})
 * </pre>
 *
 * <p><b>Ski frame.</b> {@link #renderSki} draws one ski with its binding and boot about the boot-sole centre
 * ({@link SkiStance#foot}'s point): metres, +X = the rider's left, -Z = toward the tip, the snow BOOT_SOLE (0.045 m)
 * below. Model units are 64 per metre (the skis are thin: 4x the bicycles' texel density, so the top sheet carries
 * the maker's lettering), model +Y points down like every entity model; drawn at 1/4 scale.
 *
 * <p><b>Boot.</b> The cuff is a {@code 2 BOOT_HALF} (0.266 m) square from {@link #CUFF_FRONT} to {@link #CUFF_BACK}
 * (boot-sole frame, + = back) and {@link #CUFF_TOP} high: it swallows the player's 0.234 m leg box when the leg ends
 * at the boot-sole centre (any leg axis 0 .. 0.04 m behind it fits). The cuff turns about the sole centre by the
 * shin lean the rider pose reports with {@link #setCuffLean}, so a leaning leg stays inside it.
 *
 * <p>The cube tables and textures are generated by {@code python tools/gen_ski_assets.py} (geometry in metres, UV
 * packing, per-brand painting, item icons, previews in {@code tools/preview/ski}); edit the script, not the tables.
 */
public class SkiModel extends Model {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(
            ResourceLocation.fromNamespaceAndPath(DescentMtb.MODID, "ski"), "main");
    /** Model units per metre. */
    public static final float UNITS_PER_M = 64f;
    private static final float SCALE = 16f / UNITS_PER_M;

    /** Boot cuff (boot-sole frame, metres, Y up, + Z = back): half width / depth, front and back face, top. */
    public static final float BOOT_HALF = 0.1328f, CUFF_FRONT = -0.122f, CUFF_BACK = 0.163f, CUFF_TOP = 0.31f;
    /** The pole's knob above the grip centre (m): the pole runs from y = -GRIP_TOP to {@link #poleLength} - GRIP_TOP. */
    public static final float GRIP_TOP = 0.128f;
    /** Brake arms swung down (model xRot) when the bindings are empty. */
    private static final float BRAKE_DOWN = -0.70f;
    /** Largest cuff lean either way (rad). */
    private static final float CUFF_MAX = 0.6f;

    private static final ResourceLocation[] TEXTURES = new ResourceLocation[SkiBrand.values().length];
    static {
        for (SkiBrand b : SkiBrand.values()) {
            TEXTURES[b.ordinal()] = ResourceLocation.fromNamespaceAndPath(DescentMtb.MODID, "textures/entity/ski/" + b.id + ".png");
        }
    }

    /** The last model baked by a renderer (re-baked with the renderers on a resource reload). */
    private static SkiModel instance;
    /** Shin lean of each pair's rider, {left, right} (rad, + = forward), from {@link #setCuffLean}. Render thread. */
    private static final Map<MountainBikeEntity, float[]> CUFF_LEAN = new WeakHashMap<>();
    private static final float[] FOOT = new float[6];

    private final ModelPart[] ski, brake, boot, cuff, pole;

    public SkiModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        int n = SkiBrand.values().length;
        ski = new ModelPart[n];
        brake = new ModelPart[n];
        boot = new ModelPart[n];
        cuff = new ModelPart[n];
        pole = new ModelPart[n];
        for (SkiBrand b : SkiBrand.values()) {
            ModelPart p = root.getChild(b.id);
            int i = b.ordinal();
            ski[i] = p.getChild("ski");
            brake[i] = ski[i].getChild("brake");
            boot[i] = p.getChild("boot");
            cuff[i] = boot[i].getChild("cuff");
            pole[i] = p.getChild("pole");
        }
        instance = this;
    }

    /** The brand's texture (skis, bindings, boots and poles share it). */
    public static ResourceLocation texture(SkiBrand brand) {
        return TEXTURES[brand.ordinal()];
    }

    /** The render type for the skis and the poles of {@code brand}. */
    public static RenderType renderType(SkiBrand brand) {
        return RenderType.entityCutoutNoCull(texture(brand));
    }

    /** Pole length, knob to tip (m): bent GS poles 1.20, slalom 1.20, straight park poles 1.10. */
    public static float poleLength(SkiBrand brand) {
        return POLE_LENGTH[brand.ordinal()];
    }

    /** The baked model (the one the ski renderer made, or baked here on first use). */
    public static SkiModel get() {
        if (instance == null) new SkiModel(Minecraft.getInstance().getEntityModels().bakeLayer(LAYER));
        return instance;
    }

    /**
     * The rider's shin lean in each boot, so the cuffs follow the legs: radians from the ski's vertical in the ski's
     * own side plane, + = leaning forward (toward the tips). Call it every frame the skier is posed; without a call
     * the cuffs stand upright.
     */
    public static void setCuffLean(MountainBikeEntity skis, float left, float right) {
        float[] l = CUFF_LEAN.computeIfAbsent(skis, k -> new float[2]);
        l[0] = Math.max(-CUFF_MAX, Math.min(CUFF_MAX, left));
        l[1] = Math.max(-CUFF_MAX, Math.min(CUFF_MAX, right));
    }

    /**
     * Draws the pair, each ski (with binding and, when someone rides, the boot) where {@link SkiStance#foot} puts that
     * foot this frame. {@code pose} is the bike models' space: the renderer's ground point after its
     * {@code scale(-1, -1, 1)} (Y down, +X = the rider's left, -Z forward, units = blocks = metres).
     */
    public void renderPair(PoseStack pose, VertexConsumer vc, int light, int overlay, MountainBikeEntity skis, float partialTick) {
        SkiBrand brand = skis.skiBrand();
        boolean booted = skis.isVehicle();
        float[] lean = CUFF_LEAN.get(skis);
        for (int side = 1; side >= -1; side -= 2) {
            SkiStance.foot(skis, skis.rsPrev, skis.rsCur, partialTick, side, FOOT);
            pose.pushPose();
            // ski space (Y up) -> model space (Y down): y and the rotations about X and Z change sign
            pose.translate(FOOT[SkiStance.X], -FOOT[SkiStance.Y], FOOT[SkiStance.Z]);
            pose.mulPose(Axis.YP.rotation(-FOOT[SkiStance.YAW]));
            pose.mulPose(Axis.XP.rotation(-FOOT[SkiStance.PITCH]));
            pose.mulPose(Axis.ZP.rotation(FOOT[SkiStance.ROLL]));
            renderSki(pose, vc, light, overlay, brand, booted, lean == null ? 0f : lean[side > 0 ? 0 : 1]);
            pose.popPose();
        }
    }

    /**
     * One ski with its binding about the boot-sole centre, model orientation (Y down, -Z = the tip), units = metres.
     *
     * @param booted   a boot in the binding (brakes folded up) or an empty binding (no boot, brakes down)
     * @param cuffLean shin lean (rad, + = forward), see {@link #setCuffLean}
     */
    public void renderSki(PoseStack pose, VertexConsumer vc, int light, int overlay, SkiBrand brand, boolean booted, float cuffLean) {
        int i = brand.ordinal();
        pose.pushPose();
        pose.scale(SCALE, SCALE, SCALE);
        brake[i].xRot = booted ? 0f : BRAKE_DOWN;
        ski[i].render(pose, vc, light, overlay);
        if (booted) {
            cuff[i].xRot = cuffLean;
            boot[i].render(pose, vc, light, overlay);
        }
        pose.popPose();
    }

    /**
     * Draws one pole of {@code brand} in its hand frame. Buffer: {@code buffers.getBuffer(SkiModel.renderType(brand))}.
     *
     * <p><b>Pole frame</b> ({@code pose} on entry), units = metres (= blocks, the space a {@code ModelPart}'s
     * {@code translateAndRotate} leaves you in):
     * <ul>
     *   <li>origin = the centre of the grip, where the fist closes (put it at the centre of the hand);</li>
     *   <li>+Y = along the shaft toward the basket and tip: the knob is at y = -{@link #GRIP_TOP} (-0.128), the grip
     *       runs to y = +0.108, the tip ends at y = {@link #poleLength} - {@link #GRIP_TOP};</li>
     *   <li>+Z = back: the wrist strap leaves the top of the grip toward +Z, and the bent GS race poles (Atomic,
     *       Fischer) bend toward +Z (24 deg 0.2 m under the grip, then 12 deg), so they trail back under the arms in
     *       a tuck; slalom (Rossignol) and park poles are straight along +Y;</li>
     *   <li>X = across the grip (the pole is symmetric in X; use the same pole in both hands).</li>
     * </ul>
     * With the player model's arm frame (+Y down the arm toward the hand) a pole hanging straight down the arm needs
     * only a translation to the fist; aim +Y wherever the pole should point.
     */
    public static void renderPole(PoseStack pose, VertexConsumer vc, int light, int overlay, SkiBrand brand) {
        SkiModel m = get();
        pose.pushPose();
        pose.scale(SCALE, SCALE, SCALE);
        m.pole[brand.ordinal()].render(pose, vc, light, overlay);
        pose.popPose();
    }

    /** The default pair (Atomic) with an empty binding, about the boot-sole centre. */
    @Override
    public void renderToBuffer(PoseStack pose, VertexConsumer vc, int light, int overlay, int color) {
        pose.pushPose();
        pose.scale(SCALE, SCALE, SCALE);
        brake[0].xRot = BRAKE_DOWN;
        ski[0].render(pose, vc, light, overlay, color);
        pose.popPose();
    }

    // ------------------------------------------------------------------ builders for the generated tables
    private static PartDefinition bone(PartDefinition parent, String name, float x, float y, float z,
                                       float rxDeg, float ryDeg, float rzDeg) {
        return parent.addOrReplaceChild(name, CubeListBuilder.create(),
                PartPose.offsetAndRotation(x, y, z, rad(rxDeg), rad(ryDeg), rad(rzDeg)));
    }

    /** Box centred at (cx, cy, cz) in the bone's space, size (sx, sy, sz), rotation in degrees (vanilla Z-Y-X). */
    private static void cube(PartDefinition bone, String name, int u, int v, float cx, float cy, float cz,
                             float sx, float sy, float sz, float rxDeg, float ryDeg, float rzDeg) {
        bone.addOrReplaceChild(name, CubeListBuilder.create().texOffs(u, v).addBox(-sx / 2f, -sy / 2f, -sz / 2f, sx, sy, sz),
                PartPose.offsetAndRotation(cx, cy, cz, rad(rxDeg), rad(ryDeg), rad(rzDeg)));
    }

    private static float rad(float deg) {
        return deg * ((float) Math.PI / 180f);
    }

    // ------------------------------------------------------------------ geometry (generated)
    // <GENERATED>
    /** Texture size of every brand's texture (generated). */
    public static final int TEX_W = 256, TEX_H = 256;
    /** Pole length (knob to tip, m) by {@link SkiBrand#ordinal()} (generated). */
    private static final float[] POLE_LENGTH = {1.2000f, 1.2000f, 1.2000f, 1.1000f, 1.1000f, 1.1000f};

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        brand_atomic_redster_g9(root);
        brand_rossignol_hero_st(root);
        brand_fischer_rc4_wc(root);
        brand_armada_arv_96(root);
        brand_line_chronic_101(root);
        brand_faction_prodigy_2(root);
        return LayerDefinition.create(mesh, TEX_W, TEX_H);
    }

    private static void brand_atomic_redster_g9(PartDefinition root) {
        PartDefinition brand = bone(root, "atomic_redster_g9", 0f, 0f, 0f, 0f, 0f, 0f);
        PartDefinition ski = bone(brand, "ski", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base0", 115, 117, 0.0000f, 2.7520f, -49.5000f, 8.0000f, 0.2560f, 7.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core0", 146, 117, 0.0000f, 2.3360f, -49.5000f, 8.0000f, 0.5760f, 7.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base1", 0, 89, 0.0000f, 2.7520f, -39.0000f, 7.0000f, 0.2560f, 14.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core1", 43, 89, 0.0000f, 2.2880f, -39.0000f, 7.0000f, 0.6720f, 14.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base2", 211, 89, 0.0000f, 2.7520f, -27.0000f, 6.0000f, 0.2560f, 10.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core2", 0, 105, 0.0000f, 2.2400f, -27.0000f, 6.0000f, 0.7680f, 10.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base3", 33, 105, 0.0000f, 2.7520f, -17.0000f, 6.0000f, 0.2560f, 10.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core3", 66, 105, 0.0000f, 2.2080f, -17.0000f, 6.0000f, 0.8320f, 10.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base4", 99, 105, 0.0000f, 2.7520f, -7.0000f, 6.0000f, 0.2560f, 10.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core4", 132, 105, 0.0000f, 2.2080f, -7.0000f, 6.0000f, 0.8320f, 10.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base5", 177, 117, 0.0000f, 2.7520f, 1.5000f, 5.0000f, 0.2560f, 7.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core5", 202, 117, 0.0000f, 2.2080f, 1.5000f, 5.0000f, 0.8320f, 7.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base6", 0, 69, 0.0000f, 2.7520f, 14.0000f, 6.0000f, 0.2560f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core6", 49, 69, 0.0000f, 2.2080f, 14.0000f, 6.0000f, 0.8320f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base7", 98, 69, 0.0000f, 2.7520f, 32.0000f, 6.0000f, 0.2560f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core7", 147, 69, 0.0000f, 2.2560f, 32.0000f, 6.0000f, 0.7360f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base8", 86, 89, 0.0000f, 2.7520f, 48.0000f, 7.0000f, 0.2560f, 14.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core8", 129, 89, 0.0000f, 2.3200f, 48.0000f, 7.0000f, 0.6080f, 14.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip0", 158, 128, 0.0000f, 2.4721f, -54.4751f, 8.0000f, 0.6080f, 3.0000f, -4.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip1", 181, 128, 0.0000f, 2.0928f, -57.4034f, 8.0000f, 0.5440f, 3.0000f, -12.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip2", 204, 128, 0.0000f, 1.2854f, -60.2415f, 7.0000f, 0.4800f, 3.0000f, -21.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip3", 45, 135, 0.0000f, 0.2834f, -62.4851f, 5.0000f, 0.4352f, 2.0000f, -30.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip4", 216, 135, 0.0000f, -0.4773f, -63.7516f, 3.0000f, 0.3840f, 1.0000f, -36.0000f, -0.0000f, 0.0000f);
        cube(ski, "plate_lower", 0, 0, 0.0000f, 1.5360f, -1.2800f, 4.0000f, 0.5120f, 40.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "plate_upper", 89, 0, 0.0000f, 1.0560f, -1.1200f, 4.0000f, 0.4480f, 36.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_afd", 33, 128, 0.0000f, 0.4320f, -10.5600f, 4.0000f, 0.8000f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_body", 0, 117, 0.0000f, -0.7360f, -14.9760f, 5.0000f, 3.1360f, 6.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_nose", 125, 128, 0.0000f, -0.7680f, -18.4320f, 4.0000f, 1.9200f, 3.0000f, 32.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_wings", 225, 128, 0.0000f, -1.0880f, -11.7120f, 7.0000f, 1.6640f, 1.7920f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_track", 178, 89, 0.0000f, 0.5760f, 13.2800f, 4.0000f, 0.5120f, 12.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_pad", 0, 135, 0.0000f, 0.4320f, 8.9600f, 4.0000f, 0.8000f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_body", 63, 117, 0.0000f, -1.1840f, 14.7200f, 4.0000f, 4.0320f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_cup", 52, 128, 0.0000f, -1.7920f, 11.8080f, 6.0000f, 2.0480f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_lever", 71, 128, 0.0000f, -2.1760f, 18.2400f, 3.0000f, 0.7680f, 5.0000f, -16.6992f, -0.0000f, 0.0000f);
        PartDefinition brake = bone(ski, "brake", 0.0000f, 1.5360f, 8.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(brake, "brake_arm_l", 23, 117, 2.8520f, -0.2240f, 4.3840f, 0.3840f, 0.3840f, 9.0000f, 2.0902f, -0.0000f, 0.0000f);
        cube(brake, "brake_pad_l", 140, 128, 2.8520f, -0.1280f, 9.2160f, 0.8960f, 1.2800f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(brake, "brake_arm_r", 43, 117, -2.8520f, -0.2240f, 4.3840f, 0.3840f, 0.3840f, 9.0000f, 2.0902f, -0.0000f, 0.0000f);
        cube(brake, "brake_pad_r", 149, 128, -2.8520f, -0.1280f, 9.2160f, 0.8960f, 1.2800f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        PartDefinition boot = bone(brand, "boot", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "sole_rear", 148, 42, 0.0000f, -0.6080f, 1.5000f, 16.0000f, 1.6000f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "sole_front", 0, 128, 0.0000f, -0.6080f, -9.5000f, 12.0000f, 1.6000f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "toe_lug", 60, 135, 0.0000f, -0.6400f, -11.8750f, 6.0000f, 1.2800f, 0.7500f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "heel_lug", 75, 135, 0.0000f, -0.6400f, 10.8750f, 6.0000f, 1.2800f, 0.7500f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "shell", 0, 42, 0.0000f, -4.8320f, 1.2500f, 16.0000f, 6.9760f, 19.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "toe_box", 82, 117, 0.0000f, -3.4880f, -9.2500f, 12.0000f, 4.2880f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "instep", 207, 105, 0.0000f, -5.2480f, -8.7040f, 13.0000f, 4.4800f, 5.0000f, 51.3402f, -0.0000f, 0.0000f);
        cube(boot, "buckle_toe", 158, 135, 0.0000f, -6.1760f, -10.0160f, 13.0000f, 0.6400f, 0.9997f, 50.1944f, -0.0000f, 0.0000f);
        cube(boot, "buckle_instep", 187, 135, 0.0000f, -8.1600f, -8.4800f, 13.0000f, 0.6400f, 0.9997f, 50.1944f, -0.0000f, 0.0000f);
        PartDefinition cuff = bone(boot, "cuff", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "cuff", 170, 0, 0.0000f, -13.5040f, 1.2500f, 17.0000f, 12.6720f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "tongue", 196, 69, 0.0000f, -13.4400f, -7.8500f, 10.0000f, 14.3360f, 1.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "spoiler", 190, 105, 0.0000f, -14.5280f, 10.3250f, 7.0000f, 9.8560f, 0.6500f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "strap", 71, 42, 0.0000f, -17.9840f, 1.0000f, 18.0000f, 1.9200f, 20.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "buckle_c0", 90, 135, 0.0000f, -11.2640f, -8.5600f, 16.0000f, 1.0240f, 0.3800f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "lever_c0", 103, 128, 8.7500f, -11.2640f, -6.4500f, 0.7000f, 1.4080f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "buckle_c1", 124, 135, 0.0000f, -14.4640f, -8.5600f, 16.0000f, 1.0240f, 0.3800f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "lever_c1", 114, 128, 8.7500f, -14.4640f, -6.4500f, 0.7000f, 1.4080f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        PartDefinition pole = bone(brand, "pole", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "grip", 219, 69, 0.0000f, -0.5120f, 0.0000f, 3.0000f, 12.8000f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "grip_knob", 88, 128, 0.0000f, -7.4240f, -0.1280f, 3.0000f, 1.5360f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "strap", 165, 105, 0.0000f, -2.6240f, 3.2640f, 1.5360f, 0.2560f, 10.0000f, -69.1791f, -0.0000f, 0.0000f);
        cube(pole, "shaft0", 172, 89, 0.0000f, 12.2880f, 0.0000f, 1.2160f, 12.8000f, 1.2160f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "shaft1", 241, 0, 0.0000f, 30.3814f, 5.2062f, 1.2160f, 25.6000f, 1.2160f, 24.0000f, -0.0000f, 0.0000f);
        cube(pole, "shaft2", 247, 0, 0.0000f, 54.2459f, 12.9995f, 1.2160f, 24.8860f, 1.2160f, 12.0000f, -0.0000f, 0.0000f);
        cube(pole, "ferrule", 41, 135, 0.0000f, 67.4499f, 15.8061f, 0.7040f, 2.3680f, 0.7040f, 12.0000f, -0.0000f, 0.0000f);
        cube(pole, "basket_a", 15, 135, 0.0000f, 62.6609f, 14.7882f, 3.0000f, 0.5120f, 3.0000f, 12.0000f, -0.0000f, 0.0000f);
        cube(pole, "basket_b", 28, 135, 0.0000f, 62.6609f, 14.7882f, 3.0000f, 0.5120f, 3.0000f, 16.7308f, 43.7612f, 11.7451f);
    }

    private static void brand_rossignol_hero_st(PartDefinition root) {
        PartDefinition brand = bone(root, "rossignol_hero_st", 0f, 0f, 0f, 0f, 0f, 0f);
        PartDefinition ski = bone(brand, "ski", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base0", 165, 140, 0.0000f, 2.7520f, -43.5000f, 9.0000f, 0.2560f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core0", 194, 140, 0.0000f, 2.3360f, -43.5000f, 9.0000f, 0.5760f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base1", 198, 127, 0.0000f, 2.7520f, -37.0000f, 8.0000f, 0.2560f, 8.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core1", 0, 140, 0.0000f, 2.3040f, -37.0000f, 8.0000f, 0.6400f, 8.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base2", 196, 109, 0.0000f, 2.7520f, -27.5000f, 7.0000f, 0.2560f, 11.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core2", 0, 127, 0.0000f, 2.2400f, -27.5000f, 7.0000f, 0.7680f, 11.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base3", 0, 90, 0.0000f, 2.7520f, -13.5000f, 6.0000f, 0.2560f, 17.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core3", 47, 90, 0.0000f, 2.2080f, -13.5000f, 6.0000f, 0.8320f, 17.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base4", 188, 90, 0.0000f, 2.7520f, 3.0000f, 6.0000f, 0.2560f, 16.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core4", 0, 109, 0.0000f, 2.2080f, 3.0000f, 6.0000f, 0.8320f, 16.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base5", 94, 90, 0.0000f, 2.7520f, 19.5000f, 6.0000f, 0.2560f, 17.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core5", 141, 90, 0.0000f, 2.2080f, 19.5000f, 6.0000f, 0.8320f, 17.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base6", 81, 109, 0.0000f, 2.7520f, 34.5000f, 7.0000f, 0.2560f, 13.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core6", 122, 109, 0.0000f, 2.2720f, 34.5000f, 7.0000f, 0.7040f, 13.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base7", 33, 140, 0.0000f, 2.7520f, 45.0000f, 8.0000f, 0.2560f, 8.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core7", 66, 140, 0.0000f, 2.3360f, 45.0000f, 8.0000f, 0.5760f, 8.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip0", 106, 150, 0.0000f, 2.4721f, -47.4751f, 9.0000f, 0.6080f, 3.0000f, -4.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip1", 131, 150, 0.0000f, 2.0928f, -50.4034f, 9.0000f, 0.5440f, 3.0000f, -12.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip2", 156, 150, 0.0000f, 1.2854f, -53.2415f, 8.0000f, 0.4800f, 3.0000f, -21.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip3", 0, 157, 0.0000f, 0.2834f, -55.4851f, 6.0000f, 0.4352f, 2.0000f, -30.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip4", 173, 157, 0.0000f, -0.4773f, -56.7516f, 4.0000f, 0.3840f, 1.0000f, -36.0000f, -0.0000f, 0.0000f);
        cube(ski, "plate_lower", 6, 0, 0.0000f, 1.5360f, -1.2800f, 4.0000f, 0.5120f, 40.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "plate_upper", 95, 0, 0.0000f, 1.0560f, -1.1200f, 4.0000f, 0.4480f, 36.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_afd", 223, 140, 0.0000f, 0.4320f, -10.5600f, 4.0000f, 0.8000f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_body", 116, 127, 0.0000f, -0.7360f, -14.9760f, 5.0000f, 3.1360f, 6.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_nose", 73, 150, 0.0000f, -0.7680f, -18.4320f, 4.0000f, 1.9200f, 3.0000f, 32.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_wings", 179, 150, 0.0000f, -1.0880f, -11.7120f, 7.0000f, 1.6640f, 1.7920f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_track", 163, 109, 0.0000f, 0.5760f, 13.2800f, 4.0000f, 0.5120f, 12.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_pad", 198, 150, 0.0000f, 0.4320f, 8.9600f, 4.0000f, 0.8000f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_body", 179, 127, 0.0000f, -1.1840f, 14.7200f, 4.0000f, 4.0320f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_cup", 0, 150, 0.0000f, -1.7920f, 11.8080f, 6.0000f, 2.0480f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_lever", 19, 150, 0.0000f, -2.1760f, 18.2400f, 3.0000f, 0.7680f, 5.0000f, -16.6992f, -0.0000f, 0.0000f);
        PartDefinition brake = bone(ski, "brake", 0.0000f, 1.5360f, 8.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(brake, "brake_arm_l", 139, 127, 3.3520f, -0.2240f, 4.3840f, 0.3840f, 0.3840f, 9.0000f, 2.0902f, -0.0000f, 0.0000f);
        cube(brake, "brake_pad_l", 88, 150, 3.3520f, -0.1280f, 9.2160f, 0.8960f, 1.2800f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(brake, "brake_arm_r", 159, 127, -3.3520f, -0.2240f, 4.3840f, 0.3840f, 0.3840f, 9.0000f, 2.0902f, -0.0000f, 0.0000f);
        cube(brake, "brake_pad_r", 97, 150, -3.3520f, -0.1280f, 9.2160f, 0.8960f, 1.2800f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        PartDefinition boot = bone(brand, "boot", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "sole_rear", 148, 63, 0.0000f, -0.6080f, 1.5000f, 16.0000f, 1.6000f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "sole_front", 132, 140, 0.0000f, -0.6080f, -9.5000f, 12.0000f, 1.6000f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "toe_lug", 17, 157, 0.0000f, -0.6400f, -11.8750f, 6.0000f, 1.2800f, 0.7500f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "heel_lug", 32, 157, 0.0000f, -0.6400f, 10.8750f, 6.0000f, 1.2800f, 0.7500f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "shell", 0, 63, 0.0000f, -4.8320f, 1.2500f, 16.0000f, 6.9760f, 19.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "toe_box", 99, 140, 0.0000f, -3.4880f, -9.2500f, 12.0000f, 4.2880f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "instep", 79, 127, 0.0000f, -5.2480f, -8.7040f, 13.0000f, 4.4800f, 5.0000f, 51.3402f, -0.0000f, 0.0000f);
        cube(boot, "buckle_toe", 115, 157, 0.0000f, -6.1760f, -10.0160f, 13.0000f, 0.6400f, 0.9997f, 50.1944f, -0.0000f, 0.0000f);
        cube(boot, "buckle_instep", 144, 157, 0.0000f, -8.1600f, -8.4800f, 13.0000f, 0.6400f, 0.9997f, 50.1944f, -0.0000f, 0.0000f);
        PartDefinition cuff = bone(boot, "cuff", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "cuff", 176, 0, 0.0000f, -13.5040f, 1.2500f, 17.0000f, 12.6720f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "tongue", 45, 109, 0.0000f, -13.4400f, -7.8500f, 10.0000f, 14.3360f, 1.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "spoiler", 62, 127, 0.0000f, -14.5280f, 10.3250f, 7.0000f, 9.8560f, 0.6500f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "strap", 71, 63, 0.0000f, -17.9840f, 1.0000f, 18.0000f, 1.9200f, 20.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "buckle_c0", 47, 157, 0.0000f, -11.2640f, -8.5600f, 16.0000f, 1.0240f, 0.3800f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "lever_c0", 51, 150, 8.7500f, -11.2640f, -6.4500f, 0.7000f, 1.4080f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "buckle_c1", 81, 157, 0.0000f, -14.4640f, -8.5600f, 16.0000f, 1.0240f, 0.3800f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "lever_c1", 62, 150, 8.7500f, -14.4640f, -6.4500f, 0.7000f, 1.4080f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        PartDefinition pole = bone(brand, "pole", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "grip", 68, 109, 0.0000f, -0.5120f, 0.0000f, 3.0000f, 12.8000f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "grip_knob", 36, 150, 0.0000f, -7.4240f, -0.1280f, 3.0000f, 1.5360f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "strap", 37, 127, 0.0000f, -2.6240f, 3.2640f, 1.5360f, 0.2560f, 10.0000f, -69.1791f, -0.0000f, 0.0000f);
        cube(pole, "shaft0", 0, 0, 0.0000f, 36.1280f, 0.0000f, 1.2160f, 60.4800f, 1.2160f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "ferrule", 239, 150, 0.0000f, 67.4240f, 0.0000f, 0.7040f, 2.3680f, 0.7040f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "basket_a", 213, 150, 0.0000f, 62.5280f, 0.0000f, 3.0000f, 0.5120f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "basket_b", 226, 150, 0.0000f, 62.5280f, 0.0000f, 3.0000f, 0.5120f, 3.0000f, 0.0000f, 45.0000f, 0.0000f);
    }

    private static void brand_fischer_rc4_wc(PartDefinition root) {
        PartDefinition brand = bone(root, "fischer_rc4_wc", 0f, 0f, 0f, 0f, 0f, 0f);
        PartDefinition ski = bone(brand, "ski", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base0", 74, 109, 0.0000f, 2.7520f, -43.0000f, 8.0000f, 0.2560f, 10.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core0", 111, 109, 0.0000f, 2.3200f, -43.0000f, 8.0000f, 0.6080f, 10.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base1", 181, 89, 0.0000f, 2.7520f, -31.5000f, 7.0000f, 0.2560f, 13.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core1", 0, 109, 0.0000f, 2.2560f, -31.5000f, 7.0000f, 0.7360f, 13.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base2", 122, 135, 0.0000f, 2.7520f, -23.5000f, 6.0000f, 0.2560f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core2", 141, 135, 0.0000f, 2.2240f, -23.5000f, 6.0000f, 0.8000f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base3", 0, 69, 0.0000f, 2.7520f, -13.0000f, 6.0000f, 0.2560f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core3", 49, 69, 0.0000f, 2.2080f, -13.0000f, 6.0000f, 0.8320f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base4", 98, 69, 0.0000f, 2.7520f, 5.0000f, 6.0000f, 0.2560f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core4", 147, 69, 0.0000f, 2.2080f, 5.0000f, 6.0000f, 0.8320f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base5", 196, 69, 0.0000f, 2.7520f, 23.0000f, 6.0000f, 0.2560f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core5", 0, 89, 0.0000f, 2.2240f, 23.0000f, 6.0000f, 0.8000f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base6", 49, 89, 0.0000f, 2.7520f, 39.5000f, 7.0000f, 0.2560f, 15.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core6", 94, 89, 0.0000f, 2.2880f, 39.5000f, 7.0000f, 0.6720f, 15.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base7", 125, 124, 0.0000f, 2.7520f, 49.5000f, 8.0000f, 0.2560f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core7", 152, 124, 0.0000f, 2.3360f, 49.5000f, 8.0000f, 0.5760f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip0", 55, 135, 0.0000f, 2.4721f, -49.4751f, 8.0000f, 0.6080f, 3.0000f, -4.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip1", 78, 135, 0.0000f, 2.0928f, -52.4034f, 8.0000f, 0.5440f, 3.0000f, -12.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip2", 101, 135, 0.0000f, 1.2854f, -55.2415f, 7.0000f, 0.4800f, 3.0000f, -21.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip3", 224, 135, 0.0000f, 0.2834f, -57.4851f, 5.0000f, 0.4352f, 2.0000f, -30.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip4", 141, 142, 0.0000f, -0.4773f, -58.7516f, 3.0000f, 0.3840f, 1.0000f, -36.0000f, -0.0000f, 0.0000f);
        cube(ski, "plate_lower", 0, 0, 0.0000f, 1.5360f, -1.2800f, 4.0000f, 0.5120f, 40.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "plate_upper", 89, 0, 0.0000f, 1.0560f, -1.1200f, 4.0000f, 0.4480f, 36.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_afd", 179, 124, 0.0000f, 0.4320f, -10.5600f, 4.0000f, 0.8000f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_body", 227, 109, 0.0000f, -0.7360f, -14.9760f, 5.0000f, 3.1360f, 6.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_nose", 22, 135, 0.0000f, -0.7680f, -18.4320f, 4.0000f, 1.9200f, 3.0000f, 32.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_wings", 160, 135, 0.0000f, -1.0880f, -11.7120f, 7.0000f, 1.6640f, 1.7920f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_track", 41, 109, 0.0000f, 0.5760f, 13.2800f, 4.0000f, 0.5120f, 12.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_pad", 179, 135, 0.0000f, 0.4320f, 8.9600f, 4.0000f, 0.8000f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_body", 40, 124, 0.0000f, -1.1840f, 14.7200f, 4.0000f, 4.0320f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_cup", 198, 124, 0.0000f, -1.7920f, 11.8080f, 6.0000f, 2.0480f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_lever", 217, 124, 0.0000f, -2.1760f, 18.2400f, 3.0000f, 0.7680f, 5.0000f, -16.6992f, -0.0000f, 0.0000f);
        PartDefinition brake = bone(ski, "brake", 0.0000f, 1.5360f, 8.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(brake, "brake_arm_l", 0, 124, 3.3520f, -0.2240f, 4.3840f, 0.3840f, 0.3840f, 9.0000f, 2.0902f, -0.0000f, 0.0000f);
        cube(brake, "brake_pad_l", 37, 135, 3.3520f, -0.1280f, 9.2160f, 0.8960f, 1.2800f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(brake, "brake_arm_r", 20, 124, -3.3520f, -0.2240f, 4.3840f, 0.3840f, 0.3840f, 9.0000f, 2.0902f, -0.0000f, 0.0000f);
        cube(brake, "brake_pad_r", 46, 135, -3.3520f, -0.1280f, 9.2160f, 0.8960f, 1.2800f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        PartDefinition boot = bone(brand, "boot", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "sole_rear", 148, 42, 0.0000f, -0.6080f, 1.5000f, 16.0000f, 1.6000f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "sole_front", 92, 124, 0.0000f, -0.6080f, -9.5000f, 12.0000f, 1.6000f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "toe_lug", 239, 135, 0.0000f, -0.6400f, -11.8750f, 6.0000f, 1.2800f, 0.7500f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "heel_lug", 0, 142, 0.0000f, -0.6400f, 10.8750f, 6.0000f, 1.2800f, 0.7500f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "shell", 0, 42, 0.0000f, -4.8320f, 1.2500f, 16.0000f, 6.9760f, 19.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "toe_box", 59, 124, 0.0000f, -3.4880f, -9.2500f, 12.0000f, 4.2880f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "instep", 190, 109, 0.0000f, -5.2480f, -8.7040f, 13.0000f, 4.4800f, 5.0000f, 51.3402f, -0.0000f, 0.0000f);
        cube(boot, "buckle_toe", 83, 142, 0.0000f, -6.1760f, -10.0160f, 13.0000f, 0.6400f, 0.9997f, 50.1944f, -0.0000f, 0.0000f);
        cube(boot, "buckle_instep", 112, 142, 0.0000f, -8.1600f, -8.4800f, 13.0000f, 0.6400f, 0.9997f, 50.1944f, -0.0000f, 0.0000f);
        PartDefinition cuff = bone(boot, "cuff", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "cuff", 170, 0, 0.0000f, -13.5040f, 1.2500f, 17.0000f, 12.6720f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "tongue", 139, 89, 0.0000f, -13.4400f, -7.8500f, 10.0000f, 14.3360f, 1.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "spoiler", 173, 109, 0.0000f, -14.5280f, 10.3250f, 7.0000f, 9.8560f, 0.6500f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "strap", 71, 42, 0.0000f, -17.9840f, 1.0000f, 18.0000f, 1.9200f, 20.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "buckle_c0", 15, 142, 0.0000f, -11.2640f, -8.5600f, 16.0000f, 1.0240f, 0.3800f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "lever_c0", 0, 135, 8.7500f, -11.2640f, -6.4500f, 0.7000f, 1.4080f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "buckle_c1", 49, 142, 0.0000f, -14.4640f, -8.5600f, 16.0000f, 1.0240f, 0.3800f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "lever_c1", 11, 135, 8.7500f, -14.4640f, -6.4500f, 0.7000f, 1.4080f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        PartDefinition pole = bone(brand, "pole", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "grip", 162, 89, 0.0000f, -0.5120f, 0.0000f, 3.0000f, 12.8000f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "grip_knob", 234, 124, 0.0000f, -7.4240f, -0.1280f, 3.0000f, 1.5360f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "strap", 148, 109, 0.0000f, -2.6240f, 3.2640f, 1.5360f, 0.2560f, 10.0000f, -69.1791f, -0.0000f, 0.0000f);
        cube(pole, "shaft0", 175, 89, 0.0000f, 12.2880f, 0.0000f, 1.2160f, 12.8000f, 1.2160f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "shaft1", 241, 0, 0.0000f, 30.3814f, 5.2062f, 1.2160f, 25.6000f, 1.2160f, 24.0000f, -0.0000f, 0.0000f);
        cube(pole, "shaft2", 247, 0, 0.0000f, 54.2459f, 12.9995f, 1.2160f, 24.8860f, 1.2160f, 12.0000f, -0.0000f, 0.0000f);
        cube(pole, "ferrule", 220, 135, 0.0000f, 67.4499f, 15.8061f, 0.7040f, 2.3680f, 0.7040f, 12.0000f, -0.0000f, 0.0000f);
        cube(pole, "basket_a", 194, 135, 0.0000f, 62.6609f, 14.7882f, 3.0000f, 0.5120f, 3.0000f, 12.0000f, -0.0000f, 0.0000f);
        cube(pole, "basket_b", 207, 135, 0.0000f, 62.6609f, 14.7882f, 3.0000f, 0.5120f, 3.0000f, 16.7308f, 43.7612f, 11.7451f);
    }

    private static void brand_armada_arv_96(PartDefinition root) {
        PartDefinition brand = bone(root, "armada_arv_96", 0f, 0f, 0f, 0f, 0f, 0f);
        PartDefinition ski = bone(brand, "ski", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base0", 146, 113, 0.0000f, 2.7520f, -39.5000f, 10.0000f, 0.2560f, 7.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core0", 181, 113, 0.0000f, 2.3360f, -39.5000f, 10.0000f, 0.5760f, 7.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base1", 36, 96, 0.0000f, 2.7520f, -29.0000f, 9.0000f, 0.2560f, 14.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core1", 83, 96, 0.0000f, 2.2560f, -29.0000f, 9.0000f, 0.7360f, 14.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base2", 49, 78, 0.0000f, 2.7520f, -14.5000f, 8.0000f, 0.2560f, 15.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core2", 96, 78, 0.0000f, 2.2080f, -14.5000f, 8.0000f, 0.8320f, 15.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base3", 175, 57, 0.0000f, 2.7520f, 1.0000f, 8.0000f, 0.2560f, 16.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core3", 0, 78, 0.0000f, 2.2080f, 1.0000f, 8.0000f, 0.8320f, 16.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base4", 143, 78, 0.0000f, 2.7520f, 16.5000f, 8.0000f, 0.2560f, 15.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core4", 190, 78, 0.0000f, 2.2080f, 16.5000f, 8.0000f, 0.8320f, 15.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base5", 69, 57, 0.0000f, 2.7520f, 32.5000f, 9.0000f, 0.2560f, 17.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core5", 122, 57, 0.0000f, 2.2880f, 32.5000f, 9.0000f, 0.6720f, 17.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base6", 154, 139, 0.0000f, 2.7520f, 41.5000f, 10.0000f, 0.2560f, 1.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core6", 177, 139, 0.0000f, 2.3520f, 41.5000f, 10.0000f, 0.5440f, 1.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip0", 188, 125, 0.0000f, 2.4372f, -44.9739f, 10.0000f, 0.6080f, 4.0000f, -4.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip1", 217, 125, 0.0000f, 1.9366f, -48.8986f, 10.0000f, 0.5760f, 4.0000f, -11.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip2", 102, 133, 0.0000f, 1.1073f, -52.2517f, 9.0000f, 0.5120f, 3.0000f, -19.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip3", 152, 133, 0.0000f, -0.0466f, -54.9696f, 8.0000f, 0.4608f, 3.0000f, -28.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip4", 217, 133, 0.0000f, -1.3060f, -57.0870f, 6.0000f, 0.4224f, 2.0000f, -36.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip5", 200, 139, 0.0000f, -2.2002f, -58.2633f, 4.0000f, 0.3840f, 1.0000f, -42.0000f, -0.0000f, 0.0000f);
        cube(ski, "tail0", 48, 133, 0.0000f, 2.4721f, 43.4751f, 10.0000f, 0.6080f, 3.0000f, 4.0000f, -0.0000f, 0.0000f);
        cube(ski, "tail1", 75, 133, 0.0000f, 2.1081f, 46.4114f, 10.0000f, 0.5632f, 3.0000f, 11.0000f, -0.0000f, 0.0000f);
        cube(ski, "tail2", 127, 133, 0.0000f, 1.3739f, 49.2746f, 9.0000f, 0.4992f, 3.0000f, 19.0000f, -0.0000f, 0.0000f);
        cube(ski, "tail3", 198, 133, 0.0000f, 0.4680f, 51.5634f, 7.0000f, 0.4480f, 2.0000f, 27.0000f, -0.0000f, 0.0000f);
        cube(ski, "tail4", 15, 139, 0.0000f, -0.5028f, 53.2833f, 4.0000f, 0.4096f, 2.0000f, 33.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_track", 163, 96, 0.0000f, 1.6000f, -13.7600f, 4.0000f, 0.3840f, 11.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_afd", 21, 125, 0.0000f, 0.9120f, -10.5600f, 4.0000f, 1.7600f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_body", 219, 96, 0.0000f, -0.2560f, -14.9760f, 5.0000f, 4.0960f, 6.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_nose", 0, 133, 0.0000f, -0.7680f, -18.4320f, 4.0000f, 1.9200f, 3.0000f, 32.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_wings", 175, 133, 0.0000f, -1.0880f, -11.7120f, 7.0000f, 1.6640f, 1.7920f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_track", 130, 96, 0.0000f, 1.5360f, 13.2800f, 4.0000f, 0.5120f, 12.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_pad", 15, 133, 0.0000f, 0.9120f, 8.9600f, 4.0000f, 1.7600f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_turn_a", 216, 113, 0.0000f, 1.0880f, 14.2080f, 5.0000f, 1.4080f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_turn_b", 0, 125, 0.0000f, 1.0880f, 14.2080f, 5.0000f, 1.4080f, 5.0000f, 0.0000f, 45.0000f, 0.0000f);
        cube(ski, "heel_body", 127, 113, 0.0000f, -1.4080f, 14.3360f, 4.0000f, 3.8400f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_cup", 115, 125, 0.0000f, -1.7920f, 11.8080f, 6.0000f, 2.0480f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_lever", 134, 125, 0.0000f, -2.1760f, 18.2400f, 3.0000f, 0.7680f, 5.0000f, -16.6992f, -0.0000f, 0.0000f);
        PartDefinition brake = bone(ski, "brake", 0.0000f, 1.5360f, 8.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(brake, "brake_arm_l", 54, 113, 4.3520f, -0.2240f, 4.3840f, 0.3840f, 0.3840f, 9.0000f, 2.0902f, -0.0000f, 0.0000f);
        cube(brake, "brake_pad_l", 30, 133, 4.3520f, -0.1280f, 9.2160f, 0.8960f, 1.2800f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(brake, "brake_arm_r", 74, 113, -4.3520f, -0.2240f, 4.3840f, 0.3840f, 0.3840f, 9.0000f, 2.0902f, -0.0000f, 0.0000f);
        cube(brake, "brake_pad_r", 39, 133, -4.3520f, -0.1280f, 9.2160f, 0.8960f, 1.2800f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        PartDefinition boot = bone(brand, "boot", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "sole_rear", 0, 57, 0.0000f, -0.6080f, 1.5000f, 16.0000f, 1.6000f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "sole_front", 40, 125, 0.0000f, -0.6080f, -9.5000f, 12.0000f, 1.6000f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "toe_lug", 234, 133, 0.0000f, -0.6400f, -11.8750f, 6.0000f, 1.2800f, 0.7500f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "heel_lug", 0, 139, 0.0000f, -0.6400f, 10.8750f, 6.0000f, 1.2800f, 0.7500f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "shell", 77, 0, 0.0000f, -4.8320f, 1.2500f, 16.0000f, 6.9760f, 19.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "toe_box", 94, 113, 0.0000f, -3.4880f, -9.2500f, 12.0000f, 4.2880f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "instep", 17, 113, 0.0000f, -5.2480f, -8.7040f, 13.0000f, 4.4800f, 5.0000f, 51.3402f, -0.0000f, 0.0000f);
        cube(boot, "buckle_toe", 96, 139, 0.0000f, -6.1760f, -10.0160f, 13.0000f, 0.6400f, 0.9997f, 50.1944f, -0.0000f, 0.0000f);
        cube(boot, "buckle_instep", 125, 139, 0.0000f, -8.1600f, -8.4800f, 13.0000f, 0.6400f, 0.9997f, 50.1944f, -0.0000f, 0.0000f);
        PartDefinition cuff = bone(boot, "cuff", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "cuff", 6, 0, 0.0000f, -13.5040f, 1.2500f, 17.0000f, 12.6720f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "tongue", 0, 96, 0.0000f, -13.4400f, -7.8500f, 10.0000f, 14.3360f, 1.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "spoiler", 0, 113, 0.0000f, -14.5280f, 10.3250f, 7.0000f, 9.8560f, 0.6500f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "strap", 148, 0, 0.0000f, -17.9840f, 1.0000f, 18.0000f, 1.9200f, 20.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "buckle_c0", 28, 139, 0.0000f, -11.2640f, -8.5600f, 16.0000f, 1.0240f, 0.3800f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "lever_c0", 166, 125, 8.7500f, -11.2640f, -6.4500f, 0.7000f, 1.4080f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "buckle_c1", 62, 139, 0.0000f, -14.4640f, -8.5600f, 16.0000f, 1.0240f, 0.3800f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "lever_c1", 177, 125, 8.7500f, -14.4640f, -6.4500f, 0.7000f, 1.4080f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        PartDefinition pole = bone(brand, "pole", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "grip", 23, 96, 0.0000f, -0.5120f, 0.0000f, 3.0000f, 12.8000f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "grip_knob", 151, 125, 0.0000f, -7.4240f, -0.1280f, 3.0000f, 1.5360f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "strap", 194, 96, 0.0000f, -2.6240f, 3.2640f, 1.5360f, 0.2560f, 10.0000f, -69.1791f, -0.0000f, 0.0000f);
        cube(pole, "shaft0", 0, 0, 0.0000f, 32.9280f, 0.0000f, 1.1520f, 54.0800f, 1.1520f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "ferrule", 194, 133, 0.0000f, 61.0240f, 0.0000f, 0.7040f, 2.3680f, 0.7040f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "basket_a", 73, 125, 0.0000f, 56.1280f, 0.0000f, 5.0000f, 0.5120f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "basket_b", 94, 125, 0.0000f, 56.1280f, 0.0000f, 5.0000f, 0.5120f, 5.0000f, 0.0000f, 45.0000f, 0.0000f);
    }

    private static void brand_line_chronic_101(PartDefinition root) {
        PartDefinition brand = bone(root, "line_chronic_101", 0f, 0f, 0f, 0f, 0f, 0f);
        PartDefinition ski = bone(brand, "ski", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base0", 94, 78, 0.0000f, 2.7520f, -36.0000f, 10.0000f, 0.2560f, 12.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core0", 139, 78, 0.0000f, 2.3040f, -36.0000f, 10.0000f, 0.6400f, 12.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base1", 151, 108, 0.0000f, 2.7520f, -26.0000f, 9.0000f, 0.2560f, 8.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core1", 186, 108, 0.0000f, 2.2400f, -26.0000f, 9.0000f, 0.7680f, 8.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base2", 0, 78, 0.0000f, 2.7520f, -15.0000f, 9.0000f, 0.2560f, 14.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core2", 47, 78, 0.0000f, 2.2080f, -15.0000f, 9.0000f, 0.8320f, 14.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base3", 69, 57, 0.0000f, 2.7520f, 1.5000f, 8.0000f, 0.2560f, 19.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core3", 124, 57, 0.0000f, 2.2080f, 1.5000f, 8.0000f, 0.8320f, 19.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base4", 76, 94, 0.0000f, 2.7520f, 16.5000f, 9.0000f, 0.2560f, 11.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core4", 117, 94, 0.0000f, 2.2080f, 16.5000f, 9.0000f, 0.8320f, 11.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base5", 184, 78, 0.0000f, 2.7520f, 28.0000f, 9.0000f, 0.2560f, 12.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core5", 0, 94, 0.0000f, 2.2560f, 28.0000f, 9.0000f, 0.7360f, 12.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base6", 77, 108, 0.0000f, 2.7520f, 38.0000f, 10.0000f, 0.2560f, 8.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core6", 114, 108, 0.0000f, 2.3200f, 38.0000f, 10.0000f, 0.6080f, 8.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip0", 0, 129, 0.0000f, 2.4372f, -43.9739f, 10.0000f, 0.6080f, 4.0000f, -4.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip1", 29, 129, 0.0000f, 1.9366f, -47.8986f, 10.0000f, 0.5760f, 4.0000f, -11.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip2", 160, 129, 0.0000f, 1.1073f, -51.2517f, 9.0000f, 0.5120f, 3.0000f, -19.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip3", 210, 129, 0.0000f, -0.0466f, -53.9696f, 8.0000f, 0.4608f, 3.0000f, -28.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip4", 19, 135, 0.0000f, -1.3060f, -56.0870f, 6.0000f, 0.4224f, 2.0000f, -36.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip5", 205, 135, 0.0000f, -2.2002f, -57.2633f, 4.0000f, 0.3840f, 1.0000f, -42.0000f, -0.0000f, 0.0000f);
        cube(ski, "tail0", 106, 129, 0.0000f, 2.4721f, 43.4751f, 10.0000f, 0.6080f, 3.0000f, 4.0000f, -0.0000f, 0.0000f);
        cube(ski, "tail1", 133, 129, 0.0000f, 2.1081f, 46.4114f, 10.0000f, 0.5632f, 3.0000f, 11.0000f, -0.0000f, 0.0000f);
        cube(ski, "tail2", 185, 129, 0.0000f, 1.3739f, 49.2746f, 9.0000f, 0.4992f, 3.0000f, 19.0000f, -0.0000f, 0.0000f);
        cube(ski, "tail3", 0, 135, 0.0000f, 0.4680f, 51.5634f, 7.0000f, 0.4480f, 2.0000f, 27.0000f, -0.0000f, 0.0000f);
        cube(ski, "tail4", 66, 135, 0.0000f, -0.5028f, 53.2833f, 4.0000f, 0.4096f, 2.0000f, 33.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_track", 158, 94, 0.0000f, 1.6000f, -13.7600f, 4.0000f, 0.3840f, 11.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_afd", 61, 119, 0.0000f, 0.9120f, -10.5600f, 4.0000f, 1.7600f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_body", 214, 94, 0.0000f, -0.2560f, -14.9760f, 5.0000f, 4.0960f, 6.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_nose", 58, 129, 0.0000f, -0.7680f, -18.4320f, 4.0000f, 1.9200f, 3.0000f, 32.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_wings", 233, 129, 0.0000f, -1.0880f, -11.7120f, 7.0000f, 1.6640f, 1.7920f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_track", 43, 94, 0.0000f, 1.5360f, 13.2800f, 4.0000f, 0.5120f, 12.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_pad", 73, 129, 0.0000f, 0.9120f, 8.9600f, 4.0000f, 1.7600f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_turn_a", 19, 119, 0.0000f, 1.0880f, 14.2080f, 5.0000f, 1.4080f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_turn_b", 40, 119, 0.0000f, 1.0880f, 14.2080f, 5.0000f, 1.4080f, 5.0000f, 0.0000f, 45.0000f, 0.0000f);
        cube(ski, "heel_body", 0, 119, 0.0000f, -1.4080f, 14.3360f, 4.0000f, 3.8400f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_cup", 155, 119, 0.0000f, -1.7920f, 11.8080f, 6.0000f, 2.0480f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_lever", 174, 119, 0.0000f, -2.1760f, 18.2400f, 3.0000f, 0.7680f, 5.0000f, -16.6992f, -0.0000f, 0.0000f);
        PartDefinition brake = bone(ski, "brake", 0.0000f, 1.5360f, 8.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(brake, "brake_arm_l", 37, 108, 4.3520f, -0.2240f, 4.3840f, 0.3840f, 0.3840f, 9.0000f, 2.0902f, -0.0000f, 0.0000f);
        cube(brake, "brake_pad_l", 88, 129, 4.3520f, -0.1280f, 9.2160f, 0.8960f, 1.2800f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(brake, "brake_arm_r", 57, 108, -4.3520f, -0.2240f, 4.3840f, 0.3840f, 0.3840f, 9.0000f, 2.0902f, -0.0000f, 0.0000f);
        cube(brake, "brake_pad_r", 97, 129, -4.3520f, -0.1280f, 9.2160f, 0.8960f, 1.2800f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        PartDefinition boot = bone(brand, "boot", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "sole_rear", 0, 57, 0.0000f, -0.6080f, 1.5000f, 16.0000f, 1.6000f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "sole_front", 80, 119, 0.0000f, -0.6080f, -9.5000f, 12.0000f, 1.6000f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "toe_lug", 36, 135, 0.0000f, -0.6400f, -11.8750f, 6.0000f, 1.2800f, 0.7500f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "heel_lug", 51, 135, 0.0000f, -0.6400f, 10.8750f, 6.0000f, 1.2800f, 0.7500f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "shell", 77, 0, 0.0000f, -4.8320f, 1.2500f, 16.0000f, 6.9760f, 19.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "toe_box", 221, 108, 0.0000f, -3.4880f, -9.2500f, 12.0000f, 4.2880f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "instep", 0, 108, 0.0000f, -5.2480f, -8.7040f, 13.0000f, 4.4800f, 5.0000f, 51.3402f, -0.0000f, 0.0000f);
        cube(boot, "buckle_toe", 147, 135, 0.0000f, -6.1760f, -10.0160f, 13.0000f, 0.6400f, 0.9997f, 50.1944f, -0.0000f, 0.0000f);
        cube(boot, "buckle_instep", 176, 135, 0.0000f, -8.1600f, -8.4800f, 13.0000f, 0.6400f, 0.9997f, 50.1944f, -0.0000f, 0.0000f);
        PartDefinition cuff = bone(boot, "cuff", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "cuff", 6, 0, 0.0000f, -13.5040f, 1.2500f, 17.0000f, 12.6720f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "tongue", 179, 57, 0.0000f, -13.4400f, -7.8500f, 10.0000f, 14.3360f, 1.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "spoiler", 237, 94, 0.0000f, -14.5280f, 10.3250f, 7.0000f, 9.8560f, 0.6500f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "strap", 148, 0, 0.0000f, -17.9840f, 1.0000f, 18.0000f, 1.9200f, 20.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "buckle_c0", 79, 135, 0.0000f, -11.2640f, -8.5600f, 16.0000f, 1.0240f, 0.3800f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "lever_c0", 206, 119, 8.7500f, -11.2640f, -6.4500f, 0.7000f, 1.4080f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "buckle_c1", 113, 135, 0.0000f, -14.4640f, -8.5600f, 16.0000f, 1.0240f, 0.3800f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "lever_c1", 217, 119, 8.7500f, -14.4640f, -6.4500f, 0.7000f, 1.4080f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        PartDefinition pole = bone(brand, "pole", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "grip", 202, 57, 0.0000f, -0.5120f, 0.0000f, 3.0000f, 12.8000f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "grip_knob", 191, 119, 0.0000f, -7.4240f, -0.1280f, 3.0000f, 1.5360f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "strap", 189, 94, 0.0000f, -2.6240f, 3.2640f, 1.5360f, 0.2560f, 10.0000f, -69.1791f, -0.0000f, 0.0000f);
        cube(pole, "shaft0", 0, 0, 0.0000f, 32.9280f, 0.0000f, 1.1520f, 54.0800f, 1.1520f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "ferrule", 252, 129, 0.0000f, 61.0240f, 0.0000f, 0.7040f, 2.3680f, 0.7040f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "basket_a", 113, 119, 0.0000f, 56.1280f, 0.0000f, 5.0000f, 0.5120f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "basket_b", 134, 119, 0.0000f, 56.1280f, 0.0000f, 5.0000f, 0.5120f, 5.0000f, 0.0000f, 45.0000f, 0.0000f);
    }

    private static void brand_faction_prodigy_2(PartDefinition root) {
        PartDefinition brand = bone(root, "faction_prodigy_2", 0f, 0f, 0f, 0f, 0f, 0f);
        PartDefinition ski = bone(brand, "ski", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base0", 0, 110, 0.0000f, 2.7520f, -36.0000f, 10.0000f, 0.2560f, 8.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core0", 37, 110, 0.0000f, 2.3200f, -36.0000f, 10.0000f, 0.6080f, 8.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base1", 0, 98, 0.0000f, 2.7520f, -27.0000f, 9.0000f, 0.2560f, 10.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core1", 39, 98, 0.0000f, 2.2560f, -27.0000f, 9.0000f, 0.7360f, 10.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base2", 126, 110, 0.0000f, 2.7520f, -19.0000f, 9.0000f, 0.2560f, 6.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core2", 157, 110, 0.0000f, 2.2080f, -19.0000f, 9.0000f, 0.8320f, 6.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base3", 179, 57, 0.0000f, 2.7520f, -7.0000f, 8.0000f, 0.2560f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core3", 0, 78, 0.0000f, 2.2080f, -7.0000f, 8.0000f, 0.8320f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base4", 53, 78, 0.0000f, 2.7520f, 10.5000f, 8.0000f, 0.2560f, 17.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core4", 104, 78, 0.0000f, 2.2080f, 10.5000f, 8.0000f, 0.8320f, 17.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base5", 69, 57, 0.0000f, 2.7520f, 28.0000f, 9.0000f, 0.2560f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core5", 124, 57, 0.0000f, 2.2560f, 28.0000f, 9.0000f, 0.7360f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "base6", 148, 120, 0.0000f, 2.7520f, 39.0000f, 10.0000f, 0.2560f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "core6", 177, 120, 0.0000f, 2.3360f, 39.0000f, 10.0000f, 0.5760f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip0", 206, 120, 0.0000f, 2.4372f, -41.9739f, 10.0000f, 0.6080f, 4.0000f, -4.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip1", 0, 127, 0.0000f, 1.9366f, -45.8986f, 10.0000f, 0.5760f, 4.0000f, -11.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip2", 131, 127, 0.0000f, 1.1073f, -49.2517f, 9.0000f, 0.5120f, 3.0000f, -19.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip3", 181, 127, 0.0000f, -0.0466f, -51.9696f, 8.0000f, 0.4608f, 3.0000f, -28.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip4", 0, 133, 0.0000f, -1.3060f, -54.0870f, 6.0000f, 0.4224f, 2.0000f, -36.0000f, -0.0000f, 0.0000f);
        cube(ski, "tip5", 186, 133, 0.0000f, -2.2002f, -55.2633f, 4.0000f, 0.3840f, 1.0000f, -42.0000f, -0.0000f, 0.0000f);
        cube(ski, "tail0", 77, 127, 0.0000f, 2.4721f, 42.4751f, 10.0000f, 0.6080f, 3.0000f, 4.0000f, -0.0000f, 0.0000f);
        cube(ski, "tail1", 104, 127, 0.0000f, 2.1081f, 45.4114f, 10.0000f, 0.5632f, 3.0000f, 11.0000f, -0.0000f, 0.0000f);
        cube(ski, "tail2", 156, 127, 0.0000f, 1.3739f, 48.2746f, 9.0000f, 0.4992f, 3.0000f, 19.0000f, -0.0000f, 0.0000f);
        cube(ski, "tail3", 227, 127, 0.0000f, 0.4680f, 50.5634f, 7.0000f, 0.4480f, 2.0000f, 27.0000f, -0.0000f, 0.0000f);
        cube(ski, "tail4", 47, 133, 0.0000f, -0.5028f, 52.2833f, 4.0000f, 0.4096f, 2.0000f, 33.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_track", 224, 78, 0.0000f, 1.6000f, -13.7600f, 4.0000f, 0.3840f, 11.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_afd", 230, 110, 0.0000f, 0.9120f, -10.5600f, 4.0000f, 1.7600f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_body", 103, 98, 0.0000f, -0.2560f, -14.9760f, 5.0000f, 4.0960f, 6.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_nose", 29, 127, 0.0000f, -0.7680f, -18.4320f, 4.0000f, 1.9200f, 3.0000f, 32.0000f, -0.0000f, 0.0000f);
        cube(ski, "toe_wings", 204, 127, 0.0000f, -1.0880f, -11.7120f, 7.0000f, 1.6640f, 1.7920f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_track", 191, 78, 0.0000f, 1.5360f, 13.2800f, 4.0000f, 0.5120f, 12.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_pad", 44, 127, 0.0000f, 0.9120f, 8.9600f, 4.0000f, 1.7600f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_turn_a", 188, 110, 0.0000f, 1.0880f, 14.2080f, 5.0000f, 1.4080f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_turn_b", 209, 110, 0.0000f, 1.0880f, 14.2080f, 5.0000f, 1.4080f, 5.0000f, 0.0000f, 45.0000f, 0.0000f);
        cube(ski, "heel_body", 107, 110, 0.0000f, -1.4080f, 14.3360f, 4.0000f, 3.8400f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_cup", 75, 120, 0.0000f, -1.7920f, 11.8080f, 6.0000f, 2.0480f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(ski, "heel_lever", 94, 120, 0.0000f, -2.1760f, 18.2400f, 3.0000f, 0.7680f, 5.0000f, -16.6992f, -0.0000f, 0.0000f);
        PartDefinition brake = bone(ski, "brake", 0.0000f, 1.5360f, 8.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(brake, "brake_arm_l", 180, 98, 4.3520f, -0.2240f, 4.3840f, 0.3840f, 0.3840f, 9.0000f, 2.0902f, -0.0000f, 0.0000f);
        cube(brake, "brake_pad_l", 59, 127, 4.3520f, -0.1280f, 9.2160f, 0.8960f, 1.2800f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(brake, "brake_arm_r", 200, 98, -4.3520f, -0.2240f, 4.3840f, 0.3840f, 0.3840f, 9.0000f, 2.0902f, -0.0000f, 0.0000f);
        cube(brake, "brake_pad_r", 68, 127, -4.3520f, -0.1280f, 9.2160f, 0.8960f, 1.2800f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        PartDefinition boot = bone(brand, "boot", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "sole_rear", 0, 57, 0.0000f, -0.6080f, 1.5000f, 16.0000f, 1.6000f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "sole_front", 0, 120, 0.0000f, -0.6080f, -9.5000f, 12.0000f, 1.6000f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "toe_lug", 17, 133, 0.0000f, -0.6400f, -11.8750f, 6.0000f, 1.2800f, 0.7500f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "heel_lug", 32, 133, 0.0000f, -0.6400f, 10.8750f, 6.0000f, 1.2800f, 0.7500f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "shell", 77, 0, 0.0000f, -4.8320f, 1.2500f, 16.0000f, 6.9760f, 19.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "toe_box", 74, 110, 0.0000f, -3.4880f, -9.2500f, 12.0000f, 4.2880f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(boot, "instep", 143, 98, 0.0000f, -5.2480f, -8.7040f, 13.0000f, 4.4800f, 5.0000f, 51.3402f, -0.0000f, 0.0000f);
        cube(boot, "buckle_toe", 128, 133, 0.0000f, -6.1760f, -10.0160f, 13.0000f, 0.6400f, 0.9997f, 50.1944f, -0.0000f, 0.0000f);
        cube(boot, "buckle_instep", 157, 133, 0.0000f, -8.1600f, -8.4800f, 13.0000f, 0.6400f, 0.9997f, 50.1944f, -0.0000f, 0.0000f);
        PartDefinition cuff = bone(boot, "cuff", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "cuff", 6, 0, 0.0000f, -13.5040f, 1.2500f, 17.0000f, 12.6720f, 18.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "tongue", 155, 78, 0.0000f, -13.4400f, -7.8500f, 10.0000f, 14.3360f, 1.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "spoiler", 126, 98, 0.0000f, -14.5280f, 10.3250f, 7.0000f, 9.8560f, 0.6500f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "strap", 148, 0, 0.0000f, -17.9840f, 1.0000f, 18.0000f, 1.9200f, 20.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "buckle_c0", 60, 133, 0.0000f, -11.2640f, -8.5600f, 16.0000f, 1.0240f, 0.3800f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "lever_c0", 126, 120, 8.7500f, -11.2640f, -6.4500f, 0.7000f, 1.4080f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "buckle_c1", 94, 133, 0.0000f, -14.4640f, -8.5600f, 16.0000f, 1.0240f, 0.3800f, 0.0000f, -0.0000f, 0.0000f);
        cube(cuff, "lever_c1", 137, 120, 8.7500f, -14.4640f, -6.4500f, 0.7000f, 1.4080f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        PartDefinition pole = bone(brand, "pole", 0.0000f, 0.0000f, 0.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "grip", 178, 78, 0.0000f, -0.5120f, 0.0000f, 3.0000f, 12.8000f, 3.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "grip_knob", 111, 120, 0.0000f, -7.4240f, -0.1280f, 3.0000f, 1.5360f, 4.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "strap", 78, 98, 0.0000f, -2.6240f, 3.2640f, 1.5360f, 0.2560f, 10.0000f, -69.1791f, -0.0000f, 0.0000f);
        cube(pole, "shaft0", 0, 0, 0.0000f, 32.9280f, 0.0000f, 1.1520f, 54.0800f, 1.1520f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "ferrule", 223, 127, 0.0000f, 61.0240f, 0.0000f, 0.7040f, 2.3680f, 0.7040f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "basket_a", 33, 120, 0.0000f, 56.1280f, 0.0000f, 5.0000f, 0.5120f, 5.0000f, 0.0000f, -0.0000f, 0.0000f);
        cube(pole, "basket_b", 54, 120, 0.0000f, 56.1280f, 0.0000f, 5.0000f, 0.5120f, 5.0000f, 0.0000f, 45.0000f, 0.0000f);
    }

    // </GENERATED>
}
